import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { API_KEY_REGISTRY } from './api-key.js';

/**
 * Scaffolder for `huu init-docker`. Writes a thin compose file (and
 * optional sibling assets) into the user's repo so they can run huu
 * under Docker without copy-pasting from docker-roadmap.md.
 *
 * Pure function — no console output, no process.exit. The CLI wrapper
 * decides how to surface the result. Tests drive it directly with a
 * tmpdir.
 */

export interface InitDockerOptions {
  /** Repo root the scaffolded files should be written into. */
  targetDir: string;
  /** Image to reference in compose. Override for testing or for pinning. */
  image?: string;
  /** Overwrite existing files instead of refusing. */
  force?: boolean;
  /** Also drop scripts/huu-docker into the repo. */
  withWrapper?: boolean;
  /** Also drop .devcontainer/devcontainer.json into the repo. */
  withDevcontainer?: boolean;
}

export interface InitDockerResult {
  /** Files actually written, relative to targetDir. */
  written: string[];
  /** Files skipped because they exist and force was not set. */
  skipped: string[];
}

const DEFAULT_IMAGE = 'ghcr.io/frederico-kluser/huu:latest';

export function renderCompose(image: string): string {
  const apiKeyEnv = API_KEY_REGISTRY.map(
    (s) => `      ${s.envVar}: \${${s.envVar}:-}`,
  ).join('\n');
  return `# Generated by \`huu init-docker\`. Edit freely.
#
# Run a huu pipeline against this repo without installing anything:
#   docker compose -f compose.huu.yaml run --rm huu run pipeline.json
#
# huu is an interactive TUI, so this file uses 'run' (not 'up') with
# tty + stdin_open. The bind mount uses the host's absolute \${PWD} on
# both sides so git worktree paths stay consistent inside and out.

services:
  huu:
    image: ${image}
    pull_policy: missing
    tty: true
    stdin_open: true
    init: true
    working_dir: \${PWD}
    volumes:
      - \${PWD}:\${PWD}
    environment:
${apiKeyEnv}
      HUU_CHECK_PUSH: \${HUU_CHECK_PUSH:-}
      TERM: xterm-256color
    # Match host UID/GID so files written by the run stay owned by you.
    # On Linux you may need: export HUU_UID=\$(id -u) HUU_GID=\$(id -g)
    user: "\${HUU_UID:-0}:\${HUU_GID:-0}"
`;
}

export function renderWrapper(image: string): string {
  const apiKeyForwards = API_KEY_REGISTRY.map((s) => `    -e ${s.envVar} \\`).join('\n');
  return `#!/usr/bin/env bash
# Generated by \`huu init-docker --with-wrapper\`.
# Run \`./scripts/huu-docker run pipeline.json\` from this repo.
set -euo pipefail

IMAGE="\${HUU_IMAGE:-${image}}"

PLATFORM_FLAG=()
case "\$(uname -m)" in
    arm64|aarch64) PLATFORM_FLAG=("--platform=linux/arm64") ;;
esac

exec docker run --rm -it \\
    "\${PLATFORM_FLAG[@]}" \\
    --user "\$(id -u):\$(id -g)" \\
    -v "\$PWD:\$PWD" \\
    -w "\$PWD" \\
${apiKeyForwards}
    -e HUU_CHECK_PUSH \\
    -e TERM=xterm-256color \\
    "\$IMAGE" \\
    huu "\$@"
`;
}

export function renderDevcontainer(image: string): string {
  const remoteEnv: Record<string, string> = {
    HUU_CHECK_PUSH: '${localEnv:HUU_CHECK_PUSH}',
  };
  for (const spec of API_KEY_REGISTRY) {
    remoteEnv[spec.envVar] = `\${localEnv:${spec.envVar}}`;
  }
  // We only emit a JSON5-clean string — no comments, since some
  // devcontainer parsers in older toolchains (e.g. CI image builders)
  // are strict about JSON.
  return JSON.stringify(
    {
      name: 'huu',
      image,
      overrideCommand: false,
      runArgs: ['--init'],
      workspaceMount:
        'source=${localWorkspaceFolder},target=${localWorkspaceFolder},type=bind,consistency=cached',
      workspaceFolder: '${localWorkspaceFolder}',
      remoteUser: 'root',
      containerEnv: {
        TERM: 'xterm-256color',
        HUU_IN_CONTAINER: '1',
      },
      remoteEnv,
    },
    null,
    2,
  );
}

/**
 * Write the scaffold. Returns which files were written and which were
 * skipped (so the CLI can print an informative summary). Throws on
 * unexpected fs errors — the CLI's outer catch surfaces them.
 */
export function initDocker(options: InitDockerOptions): InitDockerResult {
  const { targetDir, image = DEFAULT_IMAGE, force = false } = options;
  const written: string[] = [];
  const skipped: string[] = [];

  type Plan = { rel: string; content: string; mode?: number };
  const plan: Plan[] = [{ rel: 'compose.huu.yaml', content: renderCompose(image) }];

  if (options.withWrapper) {
    plan.push({ rel: join('scripts', 'huu-docker'), content: renderWrapper(image), mode: 0o755 });
  }
  if (options.withDevcontainer) {
    plan.push({
      rel: join('.devcontainer', 'devcontainer.json'),
      content: renderDevcontainer(image),
    });
  }

  for (const item of plan) {
    const abs = join(targetDir, item.rel);
    if (existsSync(abs) && !force) {
      skipped.push(item.rel);
      continue;
    }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, item.content, { mode: item.mode });
    written.push(item.rel);
  }

  return { written, skipped };
}

/**
 * CLI entry point. Parses argv slice, runs the scaffolder, prints a
 * summary, and exits with a status code suitable for shell pipelines.
 * Lives in this module (not cli.tsx) so the test suite can import and
 * exercise it without spawning a subprocess.
 */
export function runInitDockerCli(args: string[], cwd: string): number {
  const force = args.includes('--force');
  const withWrapper = args.includes('--with-wrapper');
  const withDevcontainer = args.includes('--with-devcontainer');
  let image: string | undefined;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--image' && args[i + 1]) {
      image = args[i + 1];
      i++;
    }
  }

  const result = initDocker({
    targetDir: cwd,
    image,
    force,
    withWrapper,
    withDevcontainer,
  });

  for (const f of result.written) {
    console.log(`  wrote ${relative(cwd, join(cwd, f))}`);
  }
  for (const f of result.skipped) {
    console.error(`  skipped ${f} (already exists; pass --force to overwrite)`);
  }

  if (result.written.length === 0 && result.skipped.length > 0) {
    return 1; // nothing written, all targets pre-existed
  }
  return 0;
}
