import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { AgentPortBundle } from './port-allocator.js';
import type { NativeShim } from './native-shim.js';

export const AGENT_ENV_FILE = '.env.huu';
export const AGENT_BIN_DIR = '.huu-bin';
export const AGENT_BIN_SHIM = 'with-ports';

/**
 * Default port catalog for HUU_PORT_REMAP. Covers the most common framework
 * defaults so that even hard-coded `app.listen(3000)` ends up bound to a
 * per-agent port when LD_PRELOAD/DYLD_INSERT_LIBRARIES is in effect.
 *
 * The list is intentionally short — wider catchall is the `*` mapping below.
 */
const DEFAULT_REMAP_SOURCES = [
  3000, 3001, 3002, 3003, 4000, 4200, 4321, 5000, 5001, 5173, 5174,
  5432, 5433, 6379, 6380, 8000, 8001, 8080, 8081, 8443, 9000,
];

/**
 * Builds the HUU_PORT_REMAP value the C shim parses. Pairs every well-known
 * port with one of the agent's allocated extras (or recycles them if extras
 * run out), and adds a `*:HUU_PORT_HTTP` catchall so anything else still
 * lands on a unique port instead of colliding.
 */
export function buildPortRemap(bundle: AgentPortBundle): string {
  const targets = [bundle.http, bundle.db, bundle.ws, ...bundle.extras];
  const pairs = DEFAULT_REMAP_SOURCES.map((src, i) => `${src}:${targets[i % targets.length]}`);
  // Catchall last — the shim parses left-to-right, but explicit entries
  // win in the lookup loop, so order is cosmetic. Default routes any other
  // port to the agent's primary HTTP slot.
  pairs.push(`*:${bundle.http}`);
  return pairs.join(',');
}

/**
 * Writes a per-worktree env file with the agent's allocated ports. Frameworks
 * that respect dotenv (Next/Vite/Nest/Astro/dotenv) pick this up automatically;
 * for everything else, the agent prefixes commands with the shim below.
 *
 * We deliberately use a dedicated `.env.huu` filename — never `.env` or
 * `.env.local` — so we don't shadow or risk overwriting whatever the user has
 * checked into the repo.
 */
export function writeAgentEnvFile(
  worktreePath: string,
  bundle: AgentPortBundle,
  runId: string,
  shim?: NativeShim | null,
): string {
  const remap = buildPortRemap(bundle);
  const lines = [
    `# Auto-generated by huu — per-agent port allocation. Do not commit.`,
    `HUU_RUN_ID=${runId}`,
    `HUU_AGENT_ID=${bundle.agentId}`,
    ``,
    `# Primary HTTP port — most frameworks honour PORT.`,
    `PORT=${bundle.http}`,
    `HUU_PORT=${bundle.http}`,
    `HUU_PORT_HTTP=${bundle.http}`,
    `HUU_PORT_DB=${bundle.db}`,
    `HUU_PORT_WS=${bundle.ws}`,
    ...bundle.extras.map((p, i) => `HUU_PORT_EXTRA_${i + 1}=${p}`),
    ``,
    `# Convenience URLs.`,
    `DATABASE_URL=${bundle.databaseUrl}`,
    `HUU_DATABASE_URL=${bundle.databaseUrl}`,
    ``,
    `# bind() rewrite map consumed by the native shim. Even hard-coded`,
    `# app.listen(3000) gets remapped to a per-agent port at the syscall`,
    `# boundary when the shim is preloaded.`,
    `HUU_PORT_REMAP=${remap}`,
  ];
  if (shim) {
    lines.push(
      ``,
      `# Native bind() interceptor — keeps the customer code untouched while`,
      `# guaranteeing each agent binds a unique kernel port.`,
      `${shim.envVar}=${shim.libPath}`,
    );
    if (shim.os === 'darwin') {
      // macOS requires flat namespace for DYLD_INSERT_LIBRARIES to actually
      // override symbols in the loaded binary. Without this, the interposer
      // is loaded but bind() resolves to libc directly.
      lines.push(`DYLD_FORCE_FLAT_NAMESPACE=1`);
    }
  }
  lines.push('');
  const path = join(worktreePath, AGENT_ENV_FILE);
  writeFileSync(path, lines.join('\n'), { encoding: 'utf8', mode: 0o600 });
  return path;
}

/**
 * Drops a shell shim that sources `.env.huu` and execs the wrapped command.
 * Agents call `./.huu-bin/with-ports npm run dev` when the framework ignores
 * dotenv. The shim also propagates LD_PRELOAD/DYLD_INSERT_LIBRARIES into the
 * child so bind() interception survives `bash -c`-style command boundaries.
 */
export function writeAgentBinShim(worktreePath: string): string {
  const dir = join(worktreePath, AGENT_BIN_DIR);
  mkdirSync(dir, { recursive: true });
  const shimPath = join(dir, AGENT_BIN_SHIM);
  const script = `#!/usr/bin/env bash
# Auto-generated by huu — sources .env.huu (which may contain LD_PRELOAD /
# DYLD_INSERT_LIBRARIES + HUU_PORT_REMAP) and execs the wrapped command so
# agents inherit per-worktree port allocations even when the underlying tool
# ignores dotenv files.
set -e
DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
if [ -f "$DIR/.env.huu" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$DIR/.env.huu"
  set +a
fi
exec "$@"
`;
  writeFileSync(shimPath, script, { encoding: 'utf8', mode: 0o755 });
  return shimPath;
}

/**
 * Markdown block injected into the per-agent system prompt so the LLM knows
 * which ports it owns and how to use them.
 */
export function formatPortGuidanceForPrompt(
  bundle: AgentPortBundle,
  shimAvailable = false,
): string {
  const shimNote = shimAvailable
    ? `

**bind() interception is active.** Even if the customer code calls \`app.listen(3000)\` literally
or hardcodes a port in a config file, the kernel will receive your allocated port instead. You do
NOT need to modify the customer's source to avoid collisions.`
    : `

**bind() interception is NOT available on this host.** If the customer code hardcodes a port,
parallel agents will collide. In that case, prefer running the dev server only when strictly
needed and rely on \`PORT\` / \`HUU_PORT_*\` env vars for any new code you write.`;

  return `
## Port Allocation${shimNote}

Variáveis disponíveis no shell e em \`.env.huu\` no worktree:
- \`PORT\` / \`HUU_PORT_HTTP\` = ${bundle.http}
- \`HUU_PORT_DB\` = ${bundle.db}
- \`HUU_PORT_WS\` = ${bundle.ws}
- \`DATABASE_URL\` = ${bundle.databaseUrl}

Regras:
1. NUNCA hardcode portas em código novo (3000, 8080, 5173, 5432). Use as variáveis acima.
2. Frameworks que leem dotenv (Next, Vite, Nest, etc.) carregam \`.env.huu\` automaticamente.
3. Para binários que ignoram dotenv (python, go, cargo, scripts), prefixe com o shim shell:
   \`./${AGENT_BIN_DIR}/${AGENT_BIN_SHIM} <comando>\`
   Exemplo: \`./${AGENT_BIN_DIR}/${AGENT_BIN_SHIM} python -m http.server $HUU_PORT_HTTP\`
4. Extras disponíveis: \`HUU_PORT_EXTRA_1\` … \`HUU_PORT_EXTRA_${bundle.extras.length}\`.
`;
}
