/** Shared context type for extracted orchestrator modules (M7-02). */
import type { AgentStatus, AgentTask, OrchestratorState, Pipeline, RunManifest, AppConfig, ReviewSpec, ReviewFinding } from '../lib/types.js';
import type { SpawnedAgent, AgentFactory, AgentEvent } from './types.js';
import type { WorktreeManager } from '../git/worktree-manager.js';
import { PortAllocator } from './port-allocator.js';
import { AutoScaler } from './auto-scaler.js';
import { PressureLadder } from './pressure-ladder.js';
import type { GlobalScheduler } from './global-scheduler.js';

/** Internal state of the Orchestrator. All extracted functions receive this as `this`. */
export interface OrchCtx {
  activeAgents: Map<number, SpawnedAgent>;
  agents: Map<number, AgentStatus>;
  spawningIds: Set<number>;
  finalizingIds: Set<number>;
  finalizingPromises: Set<Promise<unknown>>;
  disposingPromises: Set<Promise<unknown>>;
  killedAgentIds: Set<number>;
  pausedAgentIds: Set<number>;
  restoreSessionPaths: Map<number, string>;
  reservedAges: Map<number, number>;
  reviewLockedIds: Set<number>;
  reviewAborters: Map<number, AbortController>;
  pendingTasks: AgentTask[];
  tasksById: Map<number, AgentTask>;
  retryTimeoutOverrides: Map<number, number>;
  retryingIds: Set<number>;
  runsByStep: Map<string, number>;
  executionTrace: any[];
  stageIntegrations: any[];
  checkRuns: any[];
  streamBuffers: Map<number, { assistant: any; thinking: any }>;
  subscribers: Set<any>;
  agentOutputSubscribers: Set<any>;
  worktreeManager: WorktreeManager | null;
  portAllocator: PortAllocator;
  autoScaler: AutoScaler;
  pressureLadder: PressureLadder;
  scheduler: GlobalScheduler | null;
  schedulerHandle: any;
  manifest: RunManifest | null;
  preflight: any;
  runLogger: any;
  keyPool: any;
  nativeShim: any;
  pipeline: Pipeline;
  config: AppConfig;
  agentFactory: AgentFactory;
  cwd: string;
  status: OrchestratorState['status'];
  aborted: boolean;
  stageBaseRef: string;
  nextAgentId: number;
  instanceCount: number;
  continueOnConflict: boolean;
  conflictResolverFactory?: AgentFactory;
  totalStages: number;
  currentStage: number;
  currentWave: number;
  startedAt: number;
  completedTasks: number;
  totalTasksAcrossStages: number;
  retryMergeSeq: number;
  interactiveRetry: boolean;
  pauseInsteadOfKill: boolean;
  pauseBackoffBaseMs: number;
  pauseBackoffCapMs: number;
  autoScaleDisabledByUser: boolean;
  schedulerPriority?: number;
  externalRunId?: string;
  integrationStatus: any;
  logs: any[];
  finishResolve: (() => void) | null;
  poolWakeup: (() => void) | null;
  processLogUnsubscribe: (() => void) | null;
  onLogSink: ((entry: any) => void) | undefined;
  updateAgentStatus(agentId: number, patch: Partial<AgentStatus>): void;
  log(entry: { level: string; message: string; agentId?: number; kind?: string }): void;
  emit(): void;
  dlog(cat: string, ev: string, data?: Record<string, unknown>): void;
  hasFailedCards(): boolean;
  finish(): void;
  retryTask(agentId: number, opts?: { timeoutMs?: number }): Promise<void>;
  destroyAgent(agentId: number, reason?: string): Promise<void>;
  pauseAgent(agentId: number, reason?: string): Promise<void>;
  start(): Promise<any>;
  getDemand(): number;
  activeAgentAges(): Array<{ agentId: number; startedAt: number }>;
  abandonReview(reason: string): boolean;
  spawnStats(): { spawning: number; young: number };
  trackReservedAgent(ev: 'spawn' | 'exit', agentId: number): void;
  announceAgentExit(agentId: number, cause: string): void;
  executeTaskPool(tasks: AgentTask[]): Promise<void>;
  spawnAndRun(task: AgentTask): Promise<void>;
  runReviewLoop(task: AgentTask, review: ReviewSpec, agent: SpawnedAgent, cardTimeoutMs: number): Promise<{ preempted: boolean; blocked: boolean }>;
  consumePreemptMarker(agentId: number): boolean;
  handleReviewEvent(taskAgentId: number, reviewId: number, event: AgentEvent): void;
  persistReviewFindings(agentId: number, review: ReviewSpec, findings: readonly ReviewFinding[], waived?: boolean): void;
  commitAgentWork(agentId: number, label: string): Promise<string | null>;
  branchAhead(agentId: number): Promise<boolean>;
  branchChangedFiles(agentId: number): Promise<string[]>;
  reportKeyFailure(kind: any, key: string): Promise<boolean>;
  recordWriteSetViolations(agentId: number): Promise<void>;
  finalizeAgent(agentId: number): Promise<void>;
  upsertStageIntegration(visitIndex: number, patch: any): void;
  upsertCheckRun(visitIndex: number, patch: any): void;
  runStageIntegration(stageTasks: AgentTask[], visitIndex: number): Promise<{ producedCount: number; failedCount: number }>;
  handleAgentEvent(agentId: number, event: AgentEvent): void;
  handleStreamDelta(agentId: number, role: string, text: string): void;
  emitStreamLine(agentId: number, role: string): void;
  flushStreamBuffers(agentId: number): void;
  recordRunError(reason: string): void;
  prepareStageTasks(step: any, stepIdx: number, runId: string): any;
  runCheckVisit(step: any, stepIdx: number, visitIndex: number, runs: number, integration: any, runId: string, traceEntry: any): Promise<string>;
  runWriteSetCheck(workStep: any, stageTasks: AgentTask[]): void;
  mergeStepVisit(step: any, visitIndex: number, runs: number, tasks: AgentTask[], integration: any, traceEntry: any): Promise<boolean>;
  runDagWaves(args: any): Promise<void>;
  renderPrompt(step: any, task: AgentTask): string;
  buildSystemPromptHint(step: any, task: AgentTask): string;
  initialAgentStatus(task: AgentTask): AgentStatus;
  appendAgentLog(agentId: number, message: string): void;
  bumpAction(agentId: number, action: string): void;
  flushManifestToDisk(): void;
  appendManifestEntry(agentId: number): void;
  collectFilesModified(): string[];
  mergeIntegrationStatus(stageStatus: any): void;
}
