import type { AgentTask } from '../../../lib/types.js';
import type { AgentPortBundle } from '../../port-allocator.js';
import { generateAgentSystemPrompt } from '../../agents-md-generator.js';

/**
 * Builds the role/scope/rules header sent to the agent on the first turn.
 *
 * Pi >= 0.70 dropped `setSystemPrompt()`, so we embed the role context
 * inside the user message. The Copilot SDK accepts the same blob via
 * `systemMessage: { mode: 'append', content: ... }`. Either backend gets
 * the same text, generated by `agents-md-generator` — the prompt itself
 * is backend-agnostic.
 */
export function buildAgentMessageHeader(
  task: AgentTask,
  userPrompt: string,
  cwd: string,
  ports?: AgentPortBundle,
  shimAvailable = false,
): string {
  return generateAgentSystemPrompt(
    task.agentId,
    task.files,
    userPrompt,
    task.branchName,
    cwd,
    ports,
    shimAvailable,
  );
}
