#!/usr/bin/env bash
# scripts/test-jcode-subagents.sh
# Smoke test: validates the jcode backend by spawning 3 real sub-agents as
# parallel `jcode run` subprocesses, then verifying every expected output.
#
# Each agent writes exactly ONE file into a temp repo. The harness waits for
# all agents to exit, checks that exit codes are 0 and expected outputs exist,
# and reports pass/fail for each agent.
#
# Hermetic by default:
#   JCODE_MEMORY_ENABLED=false  — zero embeddings, stateless runs
#   JCODE_NO_TELEMETRY=1        — no external telemetry
#
# Escape hatch: HUU_JCODE_HERMETIC=0 reverts to host-global jcode config.
#
# Usage:
#   ./scripts/test-jcode-subagents.sh              # full test (3 parallel agents)
#   ./scripts/test-jcode-subagents.sh --quick      # 1-agent smoke only
#   JCODE_MEMORY_ENABLED=false ./scripts/test-jcode-subagents.sh
#
# Exit 0 on full success, non-zero on any failure.

set -euo pipefail

# ---- helpers ----
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # no color

step()  { printf '\n%s[test-jcode]%s %s\n' "$GREEN" "$NC" "$*"; }
warn()  { printf '%s[WARN]%s %s\n' "$YELLOW" "$NC" "$*" >&2; }
fail()  { printf '%s[FAIL]%s %s\n' "$RED" "$NC" "$*" >&2; exit 1; }
pass()  { printf '%s[PASS]%s %s\n' "$GREEN" "$NC" "$*"; }

QUICK="${1:-}"
if [ "$QUICK" = "--quick" ]; then
  step "quick mode: single-agent smoke only"
fi

# ---- preflight: jcode binary ----
step "preflight: locating jcode"

JCODE_BIN="${JCODE_BIN:-}"
if [ -z "$JCODE_BIN" ]; then
  if command -v jcode &>/dev/null; then
    JCODE_BIN="$(command -v jcode)"
  elif [ -x "$HOME/.local/bin/jcode" ]; then
    JCODE_BIN="$HOME/.local/bin/jcode"
  else
    fail "jcode not found in PATH or ~/.local/bin/jcode. Set JCODE_BIN=/path/to/jcode."
  fi
fi

JCODE_VERSION="$("$JCODE_BIN" version 2>&1 || true)"
if ! echo "$JCODE_VERSION" | grep -qE 'v?[0-9]+\.[0-9]+'; then
  fail "jcode version check failed. Got: $JCODE_VERSION"
fi
pass "jcode found: $JCODE_BIN  ($JCODE_VERSION)"

# ---- preflight: provider profile ----
step "preflight: provider profile deepseek-v4-pro"

# Quick smoke: can jcode resolve the provider profile? A fast no-op check.
# `jcode run --help` exits 0 and doesn't need the profile — skip deep probe.
# The real validation happens when agents run.
pass "provider profile deepseek-v4-pro (validated at agent spawn time)"

# ---- hermetic env ----
if [ "${HUU_JCODE_HERMETIC:-1}" != "0" ]; then
  export JCODE_MEMORY_ENABLED="${JCODE_MEMORY_ENABLED:-false}"
  export JCODE_NO_TELEMETRY="${JCODE_NO_TELEMETRY:-1}"
  pass "hermetic mode: JCODE_MEMORY_ENABLED=$JCODE_MEMORY_ENABLED JCODE_NO_TELEMETRY=$JCODE_NO_TELEMETRY"
else
  warn "HUU_JCODE_HERMETIC=0 — host-global jcode config in use (non-hermetic)"
fi

# ---- temp repo ----
step "creating temp git repo"

SMOKE_TMP="${HUU_SMOKE_TMPDIR:-}"
if [ -z "$SMOKE_TMP" ]; then
  if [ "$(uname)" = Darwin ]; then
    SMOKE_TMP="$REPO_ROOT/.smoke-tmp"
  else
    SMOKE_TMP="${TMPDIR:-/tmp}"
  fi
fi
mkdir -p "$SMOKE_TMP"

SCRATCH=""
CLEANUP_PATHS=""

cleanup() {
  if [ -n "$CLEANUP_PATHS" ]; then
    rm -rf $CLEANUP_PATHS
  fi
  return 0
}
trap cleanup EXIT

SCRATCH="$(mktemp -d "$SMOKE_TMP/jcode-smoke.XXXXXX")"
CLEANUP_PATHS="$CLEANUP_PATHS $SCRATCH"

git init -q "$SCRATCH"
git -C "$SCRATCH" config user.email smoke-jcode@huu.test
git -C "$SCRATCH" config user.name "jcode-smoke"
echo "# JCode Smoke Test" > "$SCRATCH/README.md"
git -C "$SCRATCH" add README.md
git -C "$SCRATCH" commit -q -m "init"

pass "temp repo: $SCRATCH"

# ---- JCODE_RUN base args (shared across all agents) ----
JCODE_ARGS=(
  run
  --no-update
  --provider-profile deepseek-v4-pro
  --model deepseek-v4-pro
  --cwd "$SCRATCH"
  --quiet
)

# ---- agent definitions ----
# Each agent: (name, prompt_single_line, expected_output_file, marker)
#
# Agent 1: writes OUTPUT_README.md
AGENT1_NAME="agent-readme"
AGENT1_PROMPT="You are agent-readme — a single-purpose test agent. Create a file named OUTPUT_README.md in the current directory with this EXACT content:\n# JCode Sub-Agent Smoke Test\nGenerated by agent-readme via jcode backend.\n\nThis file was created as part of the jcode-backend validation pipeline.\n\nUse the Write tool. Do NOT read, edit, or delete any other files. After writing, output the marker \"[agent-readme] DONE\" as your last line."
AGENT1_OUTPUT="OUTPUT_README.md"
AGENT1_MARKER="[agent-readme] DONE"

# Agent 2: writes OUTPUT_COUNTER.txt
AGENT2_NAME="agent-counter"
AGENT2_PROMPT="You are agent-counter — a single-purpose test agent. Create a file named OUTPUT_COUNTER.txt in the current directory with numbers 1 through 5, one per line:\n1\n2\n3\n4\n5\n\nUse the Write tool. Do NOT read, edit, or delete any other files. After writing, output the marker \"[agent-counter] DONE\" as your last line."
AGENT2_OUTPUT="OUTPUT_COUNTER.txt"
AGENT2_MARKER="[agent-counter] DONE"

# Agent 3: lists dir and writes OUTPUT_LISTING.md
AGENT3_NAME="agent-listing"
AGENT3_PROMPT="You are agent-listing — a single-purpose test agent. Your task:\n1. Run ls -la in the current directory\n2. Create OUTPUT_LISTING.md with the directory listing\n\nUse Bash tool for ls -la, then Write tool for OUTPUT_LISTING.md. Do NOT read, edit, or delete any other files. After writing, output the marker \"[agent-listing] DONE\" as your last line."
AGENT3_OUTPUT="OUTPUT_LISTING.md"
AGENT3_MARKER="[agent-listing] DONE"

# ---- spawn agents in parallel ----
step "spawning agents in parallel"

declare -A AGENT_PIDS
declare -A AGENT_LOGS
declare -A AGENT_START_TS

run_agent() {
  local name="$1"
  local prompt="$2"
  local log="$SCRATCH/${name}.log"

  AGENT_LOGS["$name"]="$log"
  AGENT_START_TS["$name"]="$(date +%s)"

  printf '[test-jcode] spawning %s ...\n' "$name"

  # Run jcode in background.
  # The prompt is passed as the MESSAGE positional arg (last arg after --).
  # We use --quiet to suppress non-error output to stderr; stdout goes to the log.
  JCODE_MEMORY_ENABLED="${JCODE_MEMORY_ENABLED:-false}" \
  JCODE_NO_TELEMETRY="${JCODE_NO_TELEMETRY:-1}" \
    "$JCODE_BIN" "${JCODE_ARGS[@]}" "$prompt" >"$log" 2>&1 &

  AGENT_PIDS["$name"]=$!
}

run_agent "$AGENT1_NAME" "$(printf '%b' "$AGENT1_PROMPT")"

if [ "$QUICK" != "--quick" ]; then
  run_agent "$AGENT2_NAME" "$(printf '%b' "$AGENT2_PROMPT")"
  run_agent "$AGENT3_NAME" "$(printf '%b' "$AGENT3_PROMPT")"
fi

# ---- wait for all agents ----
step "waiting for agents to complete"

ALL_PASSED=true
AGENT_NAMES=("$AGENT1_NAME")
if [ "$QUICK" != "--quick" ]; then
  AGENT_NAMES+=("$AGENT2_NAME" "$AGENT3_NAME")
fi

for name in "${AGENT_NAMES[@]}"; do
  pid="${AGENT_PIDS[$name]}"
  log="${AGENT_LOGS[$name]}"
  start_ts="${AGENT_START_TS[$name]}"

  wait "$pid" || true
  exit_code=$?
  end_ts=$(date +%s)
  elapsed=$((end_ts - start_ts))

  if [ "$exit_code" -eq 0 ]; then
    pass "$name exited 0 (${elapsed}s)"
  else
    warn "$name exited $exit_code (${elapsed}s)"
    ALL_PASSED=false
  fi
done

# ---- verify outputs ----
step "verifying expected outputs"

verify_output() {
  local name="$1"
  local file="$SCRATCH/$2"
  local marker="$3"

  if [ -f "$file" ]; then
    local size
    size=$(wc -c < "$file" | tr -d ' ')
    if [ "$size" -gt 0 ]; then
      pass "$name: $2 exists (${size} bytes)"
      return 0
    else
      warn "$name: $2 exists but is EMPTY"
      ALL_PASSED=false
      return 1
    fi
  else
    warn "$name: $2 MISSING"
    ALL_PASSED=false
    return 1
  fi
}

verify_output "$AGENT1_NAME" "$AGENT1_OUTPUT" "$AGENT1_MARKER"

if [ "$QUICK" != "--quick" ]; then
  verify_output "$AGENT2_NAME" "$AGENT2_OUTPUT" "$AGENT2_MARKER"
  verify_output "$AGENT3_NAME" "$AGENT3_OUTPUT" "$AGENT3_MARKER"
fi

# ---- verify content (spot-checks) ----
step "spot-checking content"

# Agent 1: OUTPUT_README.md must contain the expected title
if [ -f "$SCRATCH/$AGENT1_OUTPUT" ]; then
  if grep -qF "# JCode Sub-Agent Smoke Test" "$SCRATCH/$AGENT1_OUTPUT"; then
    pass "agent-readme: content OK (title match)"
  else
    warn "agent-readme: content CHECK FAILED — missing expected title"
    ALL_PASSED=false
  fi
fi

# Agent 2: OUTPUT_COUNTER.txt must have exactly 5 numeric lines
if [ "$QUICK" != "--quick" ] && [ -f "$SCRATCH/$AGENT2_OUTPUT" ]; then
  COUNT=$(grep -cE '^[1-5]$' "$SCRATCH/$AGENT2_OUTPUT" 2>/dev/null || echo 0)
  if [ "$COUNT" -eq 5 ]; then
    pass "agent-counter: content OK (5 lines 1-5)"
  else
    warn "agent-counter: content CHECK FAILED — got $COUNT matching lines, expected 5"
    ALL_PASSED=false
  fi
fi

# Agent 3: OUTPUT_LISTING.md must exist and mention at least one of the other agents' files
if [ "$QUICK" != "--quick" ] && [ -f "$SCRATCH/$AGENT3_OUTPUT" ]; then
  if grep -qE "OUTPUT_README|OUTPUT_COUNTER|README" "$SCRATCH/$AGENT3_OUTPUT" 2>/dev/null; then
    pass "agent-listing: content OK (lists other outputs)"
  else
    pass "agent-listing: content OK (listing present, may not include peer files)"
  fi
fi

# ---- final report ----
step "final report"

echo ""
echo "  Agents spawned : ${#AGENT_NAMES[@]}"
echo "  Temp directory : $SCRATCH"
echo "  jcode binary   : $JCODE_BIN"
echo "  jcode version  : $JCODE_VERSION"
echo "  Memory enabled : ${JCODE_MEMORY_ENABLED:-false}"
echo "  Telemetry      : ${JCODE_NO_TELEMETRY:-1}"
echo ""

if [ "$ALL_PASSED" = true ]; then
  pass "ALL AGENTS PASSED — jcode backend smoke test OK"
  exit 0
else
  fail "SOME AGENTS FAILED — check logs in $SCRATCH/*.log"
fi
