// Refactoring pipeline. Fowler refactoring catalog + Mikado method graph +
// characterization-test baseline. REPORT-ONLY by default (no code rewrites)
// — the deliverable is a Mikado-style improvement plan, not the refactor
// itself, because safe refactoring requires step-by-step human review.
//
// References:
// - Fowler refactoring catalog: https://refactoring.com/catalog/
// - Mikado method: https://www.manning.com/books/the-mikado-method
// - Strangler Fig: https://martinfowler.com/bliki/StranglerFigApplication.html

import type { Pipeline } from '../types.js';

export const DEFAULT_PIPELINE_FILENAME = 'huu-refactor.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Refactor Plan';

const STEP1_PROMPT = `You are huu's refactoring-planner bootstrap agent. Goal: capture the current test baseline (characterization tests), scaffold \`huu-refactor.md\`, initialize \`huu-refactor-faq.json\`.

=== STEP 1 — Locate the test runner ===
Look for \`huu-tests.md\` first (created by the huu Test Suite pipeline). If absent, detect the runner heuristically:
- Node: \`npm test\`, \`npm run test\`, \`yarn test\`, \`pnpm test\`. Look at package.json scripts.
- Python: \`pytest\`, \`python -m unittest discover\`.
- Go: \`go test ./...\`.
- Rust: \`cargo test\`.
- Java: \`mvn test\` or \`gradle test\`.
- Ruby: \`bundle exec rspec\` / \`bundle exec rake test\`.

If no test runner can be identified: write \`huu-refactor.md\` with a critical-severity warning at the top: "No tests detected. Refactoring without a safety net is dangerous. Recommend running the huu Test Suite pipeline first." Skip to step 3 (still build the smell catalog, but the Mikado plan will note "blocked: no characterization tests").

=== STEP 2 — Capture the baseline ===
Run the test command and capture:
- Exit code.
- Number of tests passing / failing / skipped.
- Total runtime.

If tests pass: this is the characterization baseline. If tests already fail: STILL proceed — note in the FAQ that baseline was red, and any refactoring recommendation must be conditioned on "fix the failing tests first".

=== STEP 3 — Write huu-refactor.md scaffold ===
Path: \`./huu-refactor.md\`.

# huu-refactor.md — Refactoring plan (Fowler + Mikado)

> Report-only plan generated by huu's Refactor Plan pipeline. No code was rewritten.
> Methodologies: Fowler refactoring catalog (https://refactoring.com/catalog/), Mikado method (https://www.manning.com/books/the-mikado-method).

## 1. Baseline
- Test runner: <command>
- Baseline status: <green | red | none>
- Tests passing: <N> / <total>
- Baseline run timestamp: <ISO 8601>

## 2. Code smells catalog (per-file)
(filled in by step 2)

## 3. Top 5 targets
(filled in by step 3)

## 4. Mikado graph
(filled in by step 4)

## 5. Recommended Fowler refactorings
(filled in by step 5)

=== STEP 4 — Initialize huu-refactor-faq.json ===
Schema:
\`\`\`json
{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file>", "smell": "long-function|duplication|primitive-obsession|feature-envy|data-clumps|switch-statement|shotgun-surgery|divergent-change|inappropriate-intimacy|comments-as-deodorant|other", "severity": "info|warn|critical", "fowler_refactoring": "<catalog entry name or null>" }
\`\`\`

=== HARD RULES ===
- DO NOT modify production source code in this pipeline.
- The deliverable is a plan, not a refactor. Safe refactoring requires step-by-step human review.`;

const STEP2_PROMPT = `You are at step 2 — code-smells catalog for \`$file\`. Goal: identify Fowler-classic code smells in this ONE file and append findings to \`huu-refactor-faq.json\`. NO code changes.

=== Smell catalog (Fowler) ===
For each smell found, suggest the matching refactoring from https://refactoring.com/catalog/:

| Smell | Refactoring suggestion |
|---|---|
| Long function (>50 LOC) | Extract Function, Decompose Conditional, Replace Temp with Query |
| Long parameter list (>5 params) | Introduce Parameter Object, Preserve Whole Object, Replace Parameter with Query |
| Large class (file > 500 LOC) | Extract Class, Extract Superclass, Replace Conditional with Polymorphism |
| Duplication | Extract Function, Pull Up Method, Form Template Method |
| Primitive obsession (string/int instead of dedicated type) | Replace Primitive with Object, Replace Type Code with Class |
| Feature envy (method uses another class's data more than its own) | Move Function, Extract Function |
| Data clumps (same group of fields/params appears together) | Extract Class, Introduce Parameter Object |
| Switch / long if-else chain on a type code | Replace Conditional with Polymorphism, Replace Type Code with Subclasses |
| Shotgun surgery (one change requires editing many files) | Move Function, Move Field, Inline Class |
| Divergent change (one file changes for many reasons) | Extract Class, Split Phase |
| Inappropriate intimacy (two classes know too much about each other) | Move Function, Move Field, Hide Delegate, Change Bidirectional to Unidirectional |
| Comments-as-deodorant (a comment explaining what the next line does suggests the code itself is unclear) | Extract Function, Rename Variable, Introduce Assertion |

=== STEP 1 — Read inputs ===
- \`./huu-refactor.md\` (scaffold).
- \`./huu-refactor-faq.json\` (may be empty).
- \`$file\`.

=== STEP 2 — Scan for smells ===
For each smell instance found:
1. Pinpoint the location (function name + line range).
2. Identify the Fowler refactoring that addresses it.
3. Append:
\`\`\`json
{ "summary": "$file:<funcName> long function (78 LOC) — Extract Function", "knowledge": "<context: what the function does, why it's grown, which extracted sub-functions would emerge>", "path": "$file", "smell": "long-function", "severity": "warn|critical", "fowler_refactoring": "Extract Function" }
\`\`\`

Severity:
- info: minor (e.g. 5-line duplication).
- warn: clear violation (long function >50 LOC, params >5).
- critical: pervasive (file >500 LOC, function >150 LOC, switch chain on type code).

=== STEP 3 — Skip if \`$file\` is generated / vendored / config ===
Skip files matching: \`*.generated.*\`, \`*.min.js\`, \`dist/*\`, \`build/*\`, \`vendor/*\`, \`node_modules/*\`, generated migrations, type definitions \`*.d.ts\`.

=== HARD RULES ===
- DO NOT modify \`$file\` or any other file.
- Append-only to FAQ.
- Re-read FAQ before each append (parallel agents).`;

const STEP3_PROMPT = `You are at step 3 — pick the top 5 refactoring targets. Goal: read \`huu-refactor-faq.json\`, rank smells, and write section "3. Top 5 targets" of \`huu-refactor.md\`.

=== STEP 1 — Read all findings ===
- \`./huu-refactor-faq.json\`.
- \`./huu-refactor.md\`.

=== STEP 2 — Rank ===
Score each finding:
- critical = 5 points.
- warn = 2 points.
- info = 0 points.

Aggregate per file. Top 5 files by total score = the top 5 targets. Within each, pick the single highest-severity smell as the headline.

=== STEP 3 — Write section "3. Top 5 targets" ===
Replace the placeholder with:

\`\`\`
Each target is a file with the highest combined smell weight.
For each, the table shows the headline smell, the Fowler refactoring, and a rough impact rating.

| # | File | Headline smell | Fowler refactoring | Smells in file | Impact |
|---|---|---|---|---|---|
| 1 | src/orchestrator/runner.ts | Long function (210 LOC) | Extract Function | 8 (3 critical / 5 warn) | high |
| 2 | ... | | | | |
\`\`\`

Impact heuristic:
- high: > 3 critical smells in the same file OR the file is on the hot path (entry point, exported from index).
- medium: 1–3 critical OR > 5 warns.
- low: only warns.

=== HARD RULES ===
- DO NOT modify source code.
- DO NOT alter findings in the FAQ.
- Update ONLY section "3" of \`huu-refactor.md\`.`;

const STEP4_PROMPT = `You are at step 4 — build a Mikado graph for the top 5 targets. Goal: for each of the top 5 targets, write the dependency graph that turns the refactor into a series of leaf-first safe steps. Populate section "4. Mikado graph" of \`huu-refactor.md\`.

=== Mikado method primer (Ola Ellnestam / Daniel Brolund) ===
Steps:
1. State the GOAL — the desired end state ("Extract Function for orchestrator/runner.ts:runStage").
2. Try the naive change.
3. Find what breaks. Each breakage is a PREREQUISITE (a child node).
4. REVERT the change. Now visit the prerequisites one at a time, leaf-first.
5. Once all prerequisites are met, the goal can be done in one safe step.

Key constraint: leaves first. Never apply the goal until every prerequisite is green.

=== STEP 1 — Read inputs ===
- \`./huu-refactor.md\` (section "3. Top 5 targets" tells you what to plan for).
- \`./huu-refactor-faq.json\`.

=== STEP 2 — For each of the top 5 targets ===
Without modifying any code, REASON about what the naive refactor would touch:
- What other modules import the symbol being refactored?
- What tests exercise this code?
- What hidden coupling exists (shared state, side effects, ordering assumptions)?

Each of those becomes a prerequisite. List them.

=== STEP 3 — Write section "4. Mikado graph" ===
For each target, an ASCII Mikado tree:

\`\`\`
Target 1: Extract Function for src/orchestrator/runner.ts:runStage
└─ goal: split runStage(220 LOC) into 4 named sub-functions
   ├─ prerequisite 1: add unit tests covering runStage's 3 branches (currently only integration tests)
   │  ├─ prerequisite 1a: mock the AgentFactory in the unit tests (currently real)
   │  └─ prerequisite 1b: extract the "stage timeout" constant so tests can use a small value
   ├─ prerequisite 2: rename internal variable \`s\` → \`stage\` (it's used 47 times; bigger touch than expected)
   └─ prerequisite 3: move stage-result aggregation out of runStage and into runStageResult helper

Order of execution: leaf-first (1a, 1b, 2, 3, then 1, then goal).
\`\`\`

Repeat for targets 2–5.

=== STEP 4 — Strangler Fig hint (optional) ===
If any target is a LARGE refactor that touches > 5 files, suggest a Strangler Fig approach: introduce a façade module that the rest of the codebase imports, redirect old call sites to the new module incrementally, then delete the original. Link: https://martinfowler.com/bliki/StranglerFigApplication.html.

=== HARD RULES ===
- DO NOT modify source code.
- DO NOT execute any naive refactor — Mikado method is reason-first, code-second; this pipeline never gets to the code-second step.
- Update ONLY section "4".`;

const STEP5_PROMPT = `You are the final agent — step 5. Goal: synthesize \`huu-refactor-faq.json\` and the Mikado graphs into a final recommendation list, populate section "5. Recommended Fowler refactorings" of \`huu-refactor.md\`.

=== STEP 1 — Read inputs ===
- \`./huu-refactor.md\` (sections 1–4 already populated).
- \`./huu-refactor-faq.json\` (all findings).

=== STEP 2 — Aggregate findings by Fowler refactoring ===
Group ALL findings by their \`fowler_refactoring\` field. For each unique refactoring (e.g. "Extract Function", "Replace Conditional with Polymorphism"), count how many findings reference it.

=== STEP 3 — Write section "5. Recommended Fowler refactorings" ===
Sort by count descending. For each refactoring:

### Extract Function (12 occurrences across 8 files)
Catalog: https://refactoring.com/catalog/extractFunction.html
Why it helps here: most of the long-function smells in this codebase are functions that mix multiple concerns. Extract Function is the workhorse for this.
Top file pointers:
- src/orchestrator/runner.ts:42 — runStage()
- src/lib/git-preflight.ts:118 — validateRepo()
- ...

### Replace Conditional with Polymorphism (3 occurrences)
Catalog: https://refactoring.com/catalog/replaceConditionalWithPolymorphism.html
...

=== STEP 4 — Final summary block ===
At the bottom of section "5":

\`\`\`
Total smells: <N>
Critical: <X>
Warnings: <Y>
Unique Fowler refactorings recommended: <Z>
Recommended starting point: <target #1 from section 3>
Recommended pace: 1 leaf per PR (Mikado discipline); never bundle prerequisite + goal in one PR.
\`\`\`

=== HARD RULES ===
- DO NOT modify any source code.
- DO NOT add a "Refactor everything now" recommendation — Mikado discipline is leaf-by-leaf.
- The final report must be self-contained (a human can read it without rerunning the audit).`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Capture baseline + scaffold huu-refactor.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Code-smells catalog: $file',
        prompt: STEP2_PROMPT,
        files: [],
        scope: 'per-file',
      },
      {
        type: 'work',
        name: '3. Pick top 5 refactoring targets',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '4. Build Mikado graph per target',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. Final Fowler recommendation list',
        prompt: STEP5_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
