// Refactoring pipeline. Fowler refactoring catalog + Mikado method graph +
// characterization-test baseline + churn×complexity target ranking.
// REPORT-ONLY by default (no code rewrites) — the deliverable is a
// Mikado-style improvement plan, not the refactor itself, because safe
// refactoring requires step-by-step human review.
// A judge CheckStep validates the report before the run finishes.
//
// References:
// - Fowler refactoring catalog: https://refactoring.com/catalog/
// - Mikado method: https://www.manning.com/books/the-mikado-method
// - Strangler Fig: https://martinfowler.com/bliki/StranglerFigApplication.html
// - Characterization tests (Feathers): https://michaelfeathers.silvrback.com/characterization-testing
// - Hotspot prioritization (Tornhill, "Your Code as a Crime Scene"):
//   https://docs.enterprise.codescene.io/versions/4.0.16/guides/technical/hotspots.html

import type { Pipeline } from '../types.js';
import {
  persistenceCheck,
  reportJudgeCondition,
  targetsRecon,
  KNOWLEDGE_OPTIONAL_FIELDS_NOTE,
  KNOWLEDGE_ORDERING_NOTE,
} from './knowledge-protocol.js';

const REFACTOR_TARGETS_PATH = '.huu/audits/refactor-targets.json';
const REFACTOR_TARGETS_MAX_FILES = 30;

export const DEFAULT_PIPELINE_FILENAME = 'huu-refactor.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Refactor Plan';

const STEP1_PROMPT = `You are huu's refactoring-planner bootstrap agent. Goal: capture the current test baseline (characterization tests), scaffold \`.huu/audits/refactor.md\`, initialize \`.huu/audits/refactor-faq.json\`.

=== STEP 0 — REPORT-ONLY HARD RULE ===
You may NOT modify any file in the repo OTHER than the audit artifacts under \`.huu/audits/\` (and \`.huu/audits/.tmp/\` for working files) plus the single \`.gitignore\` adjustment described below. The deliverable is a PLAN, not a refactor. NEVER touch source code, NEVER touch package.json / requirements.txt / pyproject.toml / Cargo.toml / lockfiles. Create the output directory with \`mkdir -p .huu/audits/.tmp/refactor\` before writing.

${persistenceCheck('audits')}

=== STEP 1 — Locate the test runner ===
Look for \`huu-tests.md\` first (created by the huu Test Suite pipeline). If absent, detect the runner heuristically:
- Node: \`npm test\`, \`npm run test\`, \`yarn test\`, \`pnpm test\`. Look at package.json scripts.
- Python: \`pytest\`, \`python -m unittest discover\`.
- Go: \`go test ./...\`.
- Rust: \`cargo test\`.
- Java: \`mvn test\` or \`gradle test\`.
- Ruby: \`bundle exec rspec\` / \`bundle exec rake test\`.

If no test runner can be identified: write \`.huu/audits/refactor.md\` with a critical-severity warning at the top: "No tests detected. Refactoring without a safety net is dangerous. Recommend running the huu Test Suite pipeline first." Skip to step 3 (still build the smell catalog, but the Mikado plan will note "blocked: no characterization tests").

=== STEP 2 — Capture the baseline ===
Run the test command and capture:
- Exit code.
- Number of tests passing / failing / skipped.
- Total runtime.

If tests pass: this is the characterization baseline. If tests already fail: STILL proceed — note in the FAQ that baseline was red, and any refactoring recommendation must be conditioned on "fix the failing tests first".

Why this gate exists (Feathers, "Working Effectively with Legacy Code"): characterization tests "document your system's actual behavior, not the behavior you wish it had" — once in production, the system IS its own specification, including bug-as-feature behavior users depend on. Refactoring without them means changes to behavior go undetected.

=== STEP 3 — Write .huu/audits/refactor.md scaffold ===
Path: \`./.huu/audits/refactor.md\`.

# .huu/audits/refactor.md — Refactoring plan (Fowler + Mikado)

> Report-only plan generated by huu's Refactor Plan pipeline. No code was rewritten.
> Methodologies: Fowler refactoring catalog (https://refactoring.com/catalog/), Mikado method (https://www.manning.com/books/the-mikado-method).

## 1. Baseline
- Test runner: <command>
- Baseline status: <green | red | none>
- Tests passing: <N> / <total>
- Baseline run timestamp: <ISO 8601>

## 2. Code smells catalog (per-file fan-out)
(filled in by step 2)

## 3. Top 5 targets
(filled in by step 3)

## 4. Mikado graph
(filled in by step 4)

## 5. Recommended Fowler refactorings
(filled in by step 5)

## 6. Validation
(filled in by the final step after the judge approves)

=== STEP 4 — Initialize .huu/audits/refactor-faq.json ===
Schema:
\`\`\`json
{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file>", "smell": "long-function|duplication|primitive-obsession|feature-envy|data-clumps|switch-statement|shotgun-surgery|divergent-change|inappropriate-intimacy|comments-as-deodorant|other", "severity": "info|warn|critical", "fowler_refactoring": "<catalog entry name or null>" }
\`\`\`
${KNOWLEDGE_OPTIONAL_FIELDS_NOTE}

=== HARD RULES ===
- DO NOT modify production source code in this pipeline.
- The deliverable is a plan, not a refactor. Safe refactoring requires step-by-step human review.`;

const STEP_RECON_PROMPT = `${targetsRecon({
  role: "huu's code-smell catalog target selector",
  purpose: 'cataloging Fowler-classic code smells in',
  prefer: [
    'long files / god modules and large classes mixing many responsibilities',
    'files with duplicated logic, deep nesting, long parameter lists, or feature envy',
    'the churny core (frequently changed, high-traffic) over leaf utilities or generated code',
  ],
  hintGuide:
    'name the suspected smells here (long function, large class, duplicated code, feature envy, long parameter list)',
  maxFiles: REFACTOR_TARGETS_MAX_FILES,
})}

=== BEFORE YOU START ===
Read \`./.huu/audits/refactor.md\` section 1 — the first step captured the test baseline there. This step writes ONLY the target list; the per-file code-smells catalog that follows does the actual finding.`;

const STEP2_PROMPT = `You are the code-smells catalog for ONE file: \`$file\`. You are one of many agents running in parallel; your whole job is this single file. Goal: identify Fowler-classic code smells in this ONE file and append findings to \`.huu/audits/refactor-faq.json\`. NO code changes.

The recon step chose this file deliberately and left you a lead — start there: $hint

=== STEP 0 — SKIP RULE ===
SKIP IMMEDIATELY (no findings, no FAQ append) if \`$file\` matches: \`node_modules/\`, \`dist/\`, \`build/\`, \`out/\`, \`coverage/\`, \`.git/\`, \`vendor/\`, \`target/\`, \`__pycache__/\`, \`*.generated.*\`, \`*.min.js\`, \`*.min.css\`, \`*.d.ts\`, \`*.lock\`, \`*.snap\`.

=== Smell catalog (Fowler) ===
For each smell found, suggest the matching refactoring from https://refactoring.com/catalog/:

| Smell | Refactoring suggestion |
|---|---|
| Long function (>50 LOC) | Extract Function, Decompose Conditional, Replace Temp with Query |
| Long parameter list (>5 params) | Introduce Parameter Object, Preserve Whole Object, Replace Parameter with Query |
| Large class (file > 500 LOC) | Extract Class, Extract Superclass, Replace Conditional with Polymorphism |
| Duplication | Extract Function, Pull Up Method, Form Template Method |
| Primitive obsession (string/int instead of dedicated type) | Replace Primitive with Object, Replace Type Code with Class |
| Feature envy (method uses another class's data more than its own) | Move Function, Extract Function |
| Data clumps (same group of fields/params appears together) | Extract Class, Introduce Parameter Object |
| Switch / long if-else chain on a type code | Replace Conditional with Polymorphism, Replace Type Code with Subclasses |
| Shotgun surgery (one change requires editing many files) | Move Function, Move Field, Inline Class |
| Divergent change (one file changes for many reasons) | Extract Class, Split Phase |
| Inappropriate intimacy (two classes know too much about each other) | Move Function, Move Field, Hide Delegate, Change Bidirectional to Unidirectional |
| Comments-as-deodorant (a comment explaining what the next line does suggests the code itself is unclear) | Extract Function, Rename Variable, Introduce Assertion |

=== STEP 1 — Read inputs ===
- \`./.huu/audits/refactor.md\` (scaffold).
- \`./.huu/audits/refactor-faq.json\` (may be empty).
- \`$file\`.

=== STEP 2 — Scan for smells ===
For each smell instance found:
1. Pinpoint the location (function name + line range).
2. Identify the Fowler refactoring that addresses it.
3. Append:
\`\`\`json
{ "summary": "$file:<funcName> long function (78 LOC) — Extract Function", "knowledge": "<context: what the function does, why it's grown, which extracted sub-functions would emerge>", "path": "$file", "smell": "long-function", "severity": "warn|critical", "fowler_refactoring": "Extract Function" }
\`\`\`

Severity:
- info: minor (e.g. 5-line duplication).
- warn: clear violation (long function >50 LOC, params >5).
- critical: pervasive (file >500 LOC, function >150 LOC, switch chain on type code).

=== STEP 3 — Skip if \`$file\` is generated / vendored / config ===
Skip files matching: \`*.generated.*\`, \`*.min.js\`, \`dist/*\`, \`build/*\`, \`vendor/*\`, \`node_modules/*\`, generated migrations, type definitions \`*.d.ts\`.

=== HARD RULES ===
- DO NOT modify \`$file\` or any other file.
- Append-only to FAQ.
- Re-read FAQ before each append (parallel agents).`;

const STEP3_PROMPT = `You are at step 3 — pick the top 5 refactoring targets. Goal: read \`.huu/audits/refactor-faq.json\`, rank smells by SMELL WEIGHT × CHURN (the hotspot method), and write section "3. Top 5 targets" of \`.huu/audits/refactor.md\`.

=== WHY CHURN MATTERS ===
A smelly file nobody touches costs nothing; a smelly file changed weekly taxes every change. Tornhill's hotspot method (churn × complexity) is the evidence-based prioritizer — CodeScene's field data shows prioritized hotspots are ~5.5% of a codebase yet concentrate ~23% of fixed bugs. Reference: "Your Code as a Crime Scene" (2nd ed.).

=== STEP 1 — Read all findings ===
- \`./.huu/audits/refactor-faq.json\`.
- \`./.huu/audits/refactor.md\`.

=== STEP 2 — Mine churn ===
\`\`\`bash
git log --format=format: --name-only --since=12.month \\
  | grep -v '^$' | sort | uniq -c | sort -nr \\
  > ./.huu/audits/.tmp/refactor/churn.txt
\`\`\`
(Drop \`--since\` when the repo is younger than 12 months.)

=== STEP 3 — Rank ===
Per file:
- smell_weight = 5 × critical + 2 × warn (info = 0).
- churn = commit count from step 2 (0 when absent from the log).
- target_score = smell_weight × (1 + churn / max_churn) — a churned file scores up to 2× the same smells in a dormant file.

Top 5 files by target_score = the top 5 targets. Within each, pick the single highest-severity smell as the headline. Break ties by "priority" (1 first) then "fixability" (trivial first) when the findings carry those fields.

=== STEP 4 — Write section "3. Top 5 targets" ===
Replace the placeholder with:

\`\`\`
Ranking method: smell weight × churn (hotspot prioritization — Tornhill).
| # | File | Headline smell | Fowler refactoring | Smells in file | Churn (12mo) | Score | Impact |
|---|---|---|---|---|---|---|---|
| 1 | src/orchestrator/runner.ts | Long function (210 LOC) | Extract Function | 8 (3 critical / 5 warn) | 87 | 38.2 | high |
| 2 | ... | | | | | | |
\`\`\`

Impact heuristic:
- high: > 3 critical smells in the same file OR top-decile churn.
- medium: 1–3 critical OR > 5 warns.
- low: only warns and low churn.

=== Cleanup ===
Delete \`./.huu/audits/.tmp/refactor/churn.txt\` after writing the section.

=== HARD RULES ===
- DO NOT modify source code. Read-only git commands only.
- DO NOT alter findings in the FAQ.
- Update ONLY section "3" of \`.huu/audits/refactor.md\`.`;

const STEP4_PROMPT = `You are at step 4 — build a Mikado graph for the top 5 targets. Goal: for each of the top 5 targets, write the dependency graph that turns the refactor into a series of leaf-first safe steps. Populate section "4. Mikado graph" of \`.huu/audits/refactor.md\`.

=== STATIC Mikado planning (NOT the dynamic method) ===
The classic Mikado method (Ola Ellnestam / Daniel Brolund) is empirical:
1. State the GOAL.
2. Try the naive change.
3. Observe what breaks; each breakage becomes a PREREQUISITE.
4. REVERT and visit prerequisites leaf-first.
5. Apply the goal only once every prerequisite is green.

This pipeline runs in REPORT-ONLY mode — we cannot try-and-revert against the user's repo. We produce a STATIC Mikado-style graph instead: REASON about likely breakages based on call sites, imports, and tests, and document them as prerequisites. The output is a planning artifact, not a verified safe-to-apply graph. Acknowledge this honestly in the report.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/refactor.md\` (section "3. Top 5 targets" tells you what to plan for).
- \`./.huu/audits/refactor-faq.json\`.

=== STEP 2 — For each of the top 5 targets ===
Without modifying any code, REASON about what the naive refactor would touch:
- What other modules import the symbol being refactored?
- What tests exercise this code?
- What hidden coupling exists (shared state, side effects, ordering assumptions)?

Each of those becomes a prerequisite. List them.

=== STEP 3 — Write section "4. Mikado graph" ===
For each target, an ASCII Mikado tree:

\`\`\`
Target 1: Extract Function for src/orchestrator/runner.ts:runStage
└─ goal: split runStage(220 LOC) into 4 named sub-functions
   ├─ prerequisite 1: add unit tests covering runStage's 3 branches (currently only integration tests)
   │  ├─ prerequisite 1a: mock the AgentFactory in the unit tests (currently real)
   │  └─ prerequisite 1b: extract the "stage timeout" constant so tests can use a small value
   ├─ prerequisite 2: rename internal variable \`s\` → \`stage\` (it's used 47 times; bigger touch than expected)
   └─ prerequisite 3: move stage-result aggregation out of runStage and into runStageResult helper

Order of execution: leaf-first (1a, 1b, 2, 3, then 1, then goal).
\`\`\`

Repeat for targets 2–5.

=== STEP 4 — Strangler Fig hint (optional) ===
If any target is a LARGE refactor that touches > 5 files, suggest a Strangler Fig approach: introduce a façade module that the rest of the codebase imports, redirect old call sites to the new module incrementally, then delete the original. Link: https://martinfowler.com/bliki/StranglerFigApplication.html.

=== HARD RULES ===
- DO NOT modify source code.
- DO NOT execute any naive refactor — Mikado method is reason-first, code-second; this pipeline never gets to the code-second step.
- Update ONLY section "4".`;

const STEP5_PROMPT = `You are the final agent — step 5. Goal: synthesize \`.huu/audits/refactor-faq.json\` and the Mikado graphs into a final recommendation list, populate section "5. Recommended Fowler refactorings" of \`.huu/audits/refactor.md\`.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/refactor.md\` (sections 1–4 already populated).
- \`./.huu/audits/refactor-faq.json\` (all findings).

=== STEP 2 — Aggregate findings by Fowler refactoring ===
Group ALL findings by their \`fowler_refactoring\` field. For each unique refactoring (e.g. "Extract Function", "Replace Conditional with Polymorphism"), count how many findings reference it.

=== STEP 3 — Write section "5. Recommended Fowler refactorings" ===
Sort by count descending. ${KNOWLEDGE_ORDERING_NOTE}
For each refactoring:

### Extract Function (12 occurrences across 8 files)
Catalog: https://refactoring.com/catalog/extractFunction.html
Why it helps here: most of the long-function smells in this codebase are functions that mix multiple concerns. Extract Function is the workhorse for this.
Top file pointers:
- src/orchestrator/runner.ts:42 — runStage()
- src/lib/git-preflight.ts:118 — validateRepo()
- ...

### Replace Conditional with Polymorphism (3 occurrences)
Catalog: https://refactoring.com/catalog/replaceConditionalWithPolymorphism.html
...

=== STEP 4 — Final summary block ===
At the bottom of section "5":

\`\`\`
Total smells: <N>
Critical: <X>
Warnings: <Y>
Unique Fowler refactorings recommended: <Z>
Recommended starting point: <target #1 from section 3>
Recommended pace: 1 leaf per PR (Mikado discipline); never bundle prerequisite + goal in one PR.
\`\`\`

=== HARD RULES ===
- DO NOT modify any source code.
- DO NOT add a "Refactor everything now" recommendation — Mikado discipline is leaf-by-leaf.
- The final report must be self-contained (a human can read it without rerunning the audit).
- The counts you cite MUST match the FAQ entries exactly — the validation judge recounts them.`;

const STEP7_PROMPT = `You are the final agent — step 7 (post-validation). The judge approved the plan. Goal: stamp section "6. Validation" of \`.huu/audits/refactor.md\` and leave the working tree clean.

=== STEP 1 — Stamp the validation section ===
Replace the "## 6. Validation" placeholder with:
\`\`\`
Validated: <UTC timestamp> · smells: <total> (critical <X> / warn <Y> / info <Z>) · baseline: <green|red|none> · sections 1–5 complete.
Mikado caveat preserved: the graphs are STATIC plans (reasoned, not try-and-revert verified).
Validation gate: judge CheckStep ("approved" required to reach this step; "rework" loops back to the recommendation list, max 2 judge runs).
\`\`\`
Numbers MUST come from re-reading \`.huu/audits/refactor-faq.json\` and the report — do not invent them. Be idempotent: if the section is already stamped (a rework loop ran twice), overwrite it with fresh numbers.

=== STEP 2 — Exit hygiene ===
- Delete any leftovers under \`./.huu/audits/.tmp/refactor/\` (keep the directory).
- Confirm \`git status --porcelain\` shows changes only under \`.huu/\` (plus at most the permitted \`.gitignore\` adjustment).

=== HARD RULES ===
- DO NOT modify the findings, the graphs, or the recommendations — stamp only.
- DO NOT touch production files.`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Capture baseline + scaffold .huu/audits/refactor.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Select smell-catalog targets',
        prompt: STEP_RECON_PROMPT,
        files: [],
        scope: 'project',
        // huu appends the huu-memory-v1 MEMORY CONTRACT (path + format + cap).
        produces: REFACTOR_TARGETS_PATH,
      },
      {
        type: 'work',
        name: '3. Code-smells catalog: $file',
        prompt: STEP2_PROMPT,
        files: [],
        // Autonomous file set from the recon step — no per-file picker.
        scope: 'memory',
        filesFrom: REFACTOR_TARGETS_PATH,
        maxFiles: REFACTOR_TARGETS_MAX_FILES,
      },
      {
        type: 'work',
        name: '4. Pick top 5 refactoring targets',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. Build Mikado graph per target',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '6. Final Fowler recommendation list',
        prompt: STEP5_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'check',
        name: '7. Validate report',
        condition: reportJudgeCondition({
          reportPath: '.huu/audits/refactor.md',
          faqPath: '.huu/audits/refactor-faq.json',
          requiredSections: [
            '1. Baseline',
            '2. Code smells catalog (per-file fan-out)',
            '3. Top 5 targets',
            '4. Mikado graph',
            '5. Recommended Fowler refactorings',
          ],
          extraClauses: [
            'every top-5 target from section 3 has its own Mikado graph in section 4, each graph ends with an explicit leaf-first execution order, and section 4 keeps the STATIC-plan caveat (the graphs were reasoned, not try-and-revert verified).',
          ],
        }),
        maxRuns: 2,
        outcomes: [
          { label: 'approved', nextStepName: '8. Finalize report', default: true },
          { label: 'rework', nextStepName: '6. Final Fowler recommendation list' },
        ],
      },
      {
        type: 'work',
        name: '8. Finalize report',
        prompt: STEP7_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
