// Code-quality-audit pipeline. Sonar-style report: cyclomatic + cognitive
// complexity, function/file size, parameter count, nesting depth,
// churn×complexity hotspots, duplication, dead code. REPORT-ONLY.
// A judge CheckStep validates the report before the run finishes.
//
// Thresholds (baked into prompts, with sources):
// - Cyclomatic complexity > 10 = warn (SonarQube S1541 default), > 20 = critical (ESLint `complexity` default).
// - Cognitive complexity > 15 = warn (SonarSource S3776 default), > 30 = critical.
//   Spec: https://www.sonarsource.com/docs/CognitiveComplexity.pdf
// - Function length > 50 LOC = warn (ESLint max-lines-per-function default).
// - Parameter count > 5 = warn (between ESLint max-params=3 and Sonar S107=7).
// - Nesting depth > 4 = warn (ESLint max-depth default).
// - Duplication > 3% = warn (SonarQube "Sonar way" quality gate).
// - Hotspots: churn × complexity (Tornhill, "Your Code as a Crime Scene";
//   CodeScene data: prioritized hotspots ≈ 5.5% of a codebase concentrate
//   ~23% of fixed bugs). https://docs.enterprise.codescene.io/versions/4.0.16/guides/technical/hotspots.html

import type { Pipeline } from '../types.js';
import {
  knowledgeProtocol,
  persistenceCheck,
  reportJudgeCondition,
  targetsRecon,
  KNOWLEDGE_OPTIONAL_FIELDS_NOTE,
  KNOWLEDGE_ORDERING_NOTE,
} from './knowledge-protocol.js';

const QUALITY_TARGETS_PATH = '.huu/audits/quality-targets.json';
const QUALITY_TARGETS_MAX_FILES = 30;

export const DEFAULT_PIPELINE_FILENAME = 'huu-quality-audit.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Quality Audit';

const FAQ_PATH = './.huu/audits/quality-faq.json';
const FAQ_SCHEMA_LINE =
  '{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file or \'global\'>", "category": "complexity|hotspot|duplication|dead-code|size|composite", "severity": "info|warn|critical", "metric": { "name": "...", "value": ... } }';

const STEP1_PROMPT = `You are huu's code-quality-audit bootstrap agent. Goal: detect the project's language(s), make ephemeral complexity tools available where possible, write \`.huu/audits/quality.md\` scaffold and initialize \`.huu/audits/quality-faq.json\`.

=== STEP 0 — REPORT-ONLY HARD RULE ===
You may NOT modify any file in the repo OTHER than the audit artifacts under \`.huu/audits/\` (and \`.huu/audits/.tmp/\` for working files) plus the single \`.gitignore\` adjustment described below. If a tool requires installation, use \`npx --yes <tool>\` (Node), \`pipx run <tool>\` (Python), or vendored binaries under \`$HOME/.huu/bin/\`. NEVER touch package.json, requirements.txt, pyproject.toml, Cargo.toml, go.mod, lockfiles, or any production source. Create the output directory with \`mkdir -p .huu/audits/.tmp/quality\` before writing.

${persistenceCheck('audits')}

=== STEP 1 — Detect language(s) ===
Walk the repo and tally source files by extension. Identify the top language(s) by file count. Common targets:
- TypeScript/JavaScript: \`.ts\`, \`.tsx\`, \`.js\`, \`.jsx\`.
- Python: \`.py\`.
- Go: \`.go\`.
- Rust: \`.rs\`.
- Java: \`.java\`.
- Kotlin: \`.kt\`.
- Ruby: \`.rb\`.
- C/C++: \`.c\`, \`.cc\`, \`.cpp\`, \`.h\`, \`.hpp\`.
- C#: \`.cs\`.

Skip generated / vendored directories: \`node_modules\`, \`dist\`, \`build\`, \`out\`, \`vendor\`, \`target\`, \`__pycache__\`, \`.git\`, \`coverage\`.

=== STEP 2 — Make complexity tools available (ephemeral only) ===
EPHEMERAL ONLY. Use one-shot runners that DON'T modify the repo's manifests:

- TypeScript/JavaScript:
  - \`npx --yes eslint <args>\` (no install — npx caches under ~/.npm).
  - \`npx --yes eslint-plugin-sonarjs <args>\` (its \`cognitive-complexity\` rule implements the SonarSource spec, default 15).
  - Duplication: \`npx --yes jscpd <args>\`.
  - Unused exports: \`npx --yes ts-unused-exports <args>\`.
- Python:
  - \`pipx run radon <args>\` (cyclomatic + maintainability).
  - \`pipx run vulture <args>\` (dead code).
- Go: prefer \`go vet ./...\` (already in toolchain). For gocyclo, install to \`$HOME/.huu/bin/\` (\`GOBIN=$HOME/.huu/bin go install github.com/fzipp/gocyclo/cmd/gocyclo@latest\`) — NOT to the project.
- Rust: use \`cargo clippy\` only if already configured. Skip if not.
- Java: skip — toolchain installs are heavy and project-coupled.

If a tool isn't reachable (offline / no pipx / no node): WRITE an info-severity finding to the FAQ and fall back to grep/awk heuristics. The pipeline NEVER hard-fails on missing tooling.

=== STEP 3 — Write .huu/audits/quality.md scaffold ===
Path: \`./.huu/audits/quality.md\`. Required structure:

# .huu/audits/quality.md — Code quality audit

> Report-only audit generated by huu's Quality Audit pipeline.
> Thresholds: cyclomatic > 10 = warn (Sonar S1541), > 20 = critical; cognitive > 15 = warn (Sonar S3776), > 30 = critical; function > 50 LOC = warn; params > 5 = warn; nesting > 4 = warn; duplication > 3% = warn (Sonar way gate).
> Hotspot method: churn × complexity (Tornhill / CodeScene) — see section 3.

## 1. Project stats
- Languages detected: <list with file counts>
- Tools available: <list of complexity tools that successfully ran>
- Tools unavailable: <list with the reason>

## 2. Complexity findings
(filled in by the per-file complexity scan)

## 3. Hotspots (churn × complexity)
(filled in by step 3)

## 4. Duplication
(filled in by step 4)

## 5. Dead code
(filled in by step 5)

## 6. Composite score
(filled in by step 6)

## 7. Recommendations
(filled in by step 6)

## 8. Validation
(filled in by the final step after the judge approves)

=== STEP 4 — Initialize .huu/audits/quality-faq.json ===
Path: \`./.huu/audits/quality-faq.json\`. Same idempotent rules as other huu audits:
- Missing: write \`[]\` + newline.
- Existing valid array: leave alone.
- Corrupted: replace with \`[]\` + note in commit.

Schema:
\`\`\`json
{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file or 'global'>", "category": "complexity|hotspot|duplication|dead-code|size|composite", "severity": "info|warn|critical", "metric": { "name": "cyclomatic", "value": 17 } }
\`\`\`
${KNOWLEDGE_OPTIONAL_FIELDS_NOTE}

=== HARD RULES ===
- DO NOT modify production source code.
- DO NOT touch CI/CD config.
- The only outputs are .huu/audits/quality.md + .huu/audits/quality-faq.json (tools are ephemeral — npx/pipx/\$HOME/.huu/bin — never devDeps).`;

const STEP_RECON_PROMPT = `${targetsRecon({
  role: "huu's complexity-scan target selector",
  purpose: 'computing complexity metrics (cyclomatic, cognitive, length, nesting) for',
  prefer: [
    'files with real control flow — many branches / loops / nested conditionals',
    'large modules and orchestrators / handlers / parsers most likely to be over-complex',
    'the hot, churny core over leaf utilities, constants, types, or config',
  ],
  hintGuide: 'note why this file may score high (long functions, deep nesting, many branches, big switch)',
  maxFiles: QUALITY_TARGETS_MAX_FILES,
})}

=== BEFORE YOU START ===
Read \`./.huu/audits/quality.md\` section 1 (the scaffold step recorded which complexity tools are available, and the detected stack) — lean toward the files those tools can actually measure. This step writes ONLY the target list; the per-file complexity scan that follows does the actual metric computation.`;

const STEP2_PROMPT = `You are the per-file complexity scan for ONE file: \`$file\`. You are one of many agents running in parallel; your whole job is this single file. Goal: compute metrics (cyclomatic, cognitive complexity, function length, parameter count, nesting depth) for \`$file\` and append findings to \`.huu/audits/quality-faq.json\`. NO code changes.

The recon step chose this file deliberately and left you a lead — start there: $hint

=== STEP 0 — SKIP RULE ===
SKIP IMMEDIATELY (no findings, no FAQ append) if \`$file\` matches: \`node_modules/\`, \`dist/\`, \`build/\`, \`out/\`, \`coverage/\`, \`.git/\`, \`vendor/\`, \`target/\`, \`__pycache__/\`, \`*.generated.*\`, \`*.min.js\`, \`*.min.css\`, \`*.d.ts\`, \`*.lock\`, \`*.snap\`.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/quality.md\` (scaffold; check section 1 for which tools are available).
- \`./.huu/audits/quality-faq.json\` (may be empty or have prior findings).
- \`$file\` (the source file to analyze).

=== STEP 2 — Pick the appropriate tool ===
By extension, in order of preference:
- \`.ts/.tsx/.js/.jsx\`: try \`npx eslint --no-eslintrc --rule '{"complexity": ["error", {"max": 10}]}' "$file"\`. Fallback: AST-free heuristic (count if/else/case/for/while/&&/||/?: in the file).
- \`.py\`: \`radon cc -s -j "$file"\` (JSON output). Fallback: heuristic.
- \`.go\`: \`gocyclo "$file"\`. Fallback: heuristic.
- \`.rs\`: \`cargo clippy -- -W cognitive_complexity\` (slow; only if cargo present). Fallback: heuristic.
- \`.java/.kt\`: heuristic only (avoid heavyweight setup).
- Other: heuristic only.

=== STEP 3 — Heuristic fallback (when no tool ran) ===
Per FUNCTION (best-effort regex; not perfect but consistent):
- Cyclomatic ≈ 1 + count of \`\\bif\\b|\\belse\\b|\\bcase\\b|\\bwhen\\b|\\bfor\\b|\\bwhile\\b|&&|\\|\\||\\?\` inside the function body.
- Cognitive ≈ apply the three SonarSource rules (https://www.sonarsource.com/docs/CognitiveComplexity.pdf): +1 per flow break (if/ternary, loop, catch, else, switch as a WHOLE — not per case, each RUN of \`&&\`/\`||\`, recursion), plus +1 per nesting level for flow breaks inside other flow breaks. Method calls and early returns are free.
- Function length = lines of code between the opening and closing brace (or Python indent block).
- Parameter count = count of commas in the signature + 1 (0 if signature is empty).
- Nesting depth = max indentation level reached inside the function body.

=== STEP 4 — Score and append findings ===
For each function found:
- Cyclomatic > 20 → severity critical, category "complexity".
- Cyclomatic > 10 → severity warn.
- Cognitive > 30 → severity critical, category "complexity".
- Cognitive > 15 → severity warn (Sonar S3776 default).
- Length > 50 LOC → severity warn, category "size".
- Length > 200 LOC → severity critical.
- Parameter count > 5 → severity warn, category "size".
- Nesting depth > 4 → severity warn, category "complexity".

When both cyclomatic and cognitive flag the same function, keep BOTH metrics in one finding (cognitive is the better understandability signal; cyclomatic the better test-effort signal).

Append ONE finding per problematic function:
\`\`\`json
{ "summary": "<file>:<funcName> cyclomatic=17 cognitive=21", "knowledge": "<details>", "path": "$file", "category": "complexity", "severity": "warn", "metric": { "name": "cognitive", "value": 21 } }
\`\`\`

If \`$file\` has zero findings, append ONE info-severity summary saying so:
\`\`\`json
{ "summary": "$file: clean (all metrics under thresholds)", "knowledge": "...", "path": "$file", "category": "composite", "severity": "info" }
\`\`\`

=== HARD RULES ===
- DO NOT modify \`$file\`.
- DO NOT touch other files.
- Append-only to \`.huu/audits/quality-faq.json\` (re-read before each append; parallel agents).`;

const STEP3_PROMPT = `You are at step 3 — hotspot analysis (whole-project). Goal: rank files by churn × complexity — the Tornhill/CodeScene method — append "hotspot" findings, populate section "3. Hotspots (churn × complexity)" of \`.huu/audits/quality.md\`. NO code changes.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: step 2's per-file complexity findings are one of your two inputs — read them all before computing.

=== WHY THIS STEP EXISTS ===
Complexity only costs where you actually work. The hotspot method overlaps (a) change frequency from git history with (b) a complexity proxy; CodeScene's field data shows prioritized hotspots are ~5.5% of a codebase yet concentrate ~23% of fixed bugs — far better refactoring ROI than raw complexity ranking. Reference: Adam Tornhill, "Your Code as a Crime Scene" (2nd ed.); https://docs.enterprise.codescene.io/versions/4.0.16/guides/technical/hotspots.html

=== STEP 1 — Mine churn from git ===
\`\`\`bash
git log --format=format: --name-only --since=12.month \\
  | grep -v '^$' | sort | uniq -c | sort -nr | head -100 \\
  > ./.huu/audits/.tmp/quality/churn.txt
\`\`\`
(If the repo has <12 months of history, drop \`--since\`.) Exclude non-source paths (docs, lockfiles, generated, vendored).

=== STEP 2 — Complexity proxy per file ===
For each churned file: prefer the cognitive/cyclomatic findings from step 2 (sum of metric values for the file). For churned files step 2 did not scan, use total LOC as the proxy (CodeScene's own default proxy).

=== STEP 3 — Score and rank ===
\`hotspot_score(file) = churn_rank_weight × complexity_weight\` — normalize both to [0,1] (divide by the max observed) and multiply. Rank descending. The top ~10 files (or fewer for small repos) are the hotspots.

For each hotspot append:
\`\`\`json
{ "summary": "Hotspot: src/orchestrator/index.ts (churn 87 commits/12mo × cognitive 142)", "knowledge": "<churn count, complexity inputs, normalized score, what kind of changes the log shows (fixes vs features)>", "path": "src/orchestrator/index.ts", "category": "hotspot", "severity": "warn", "metric": { "name": "hotspot_score", "value": 0.83 }, "priority": 1 }
\`\`\`
Severity: warn by default; critical when the hotspot ALSO carries a critical complexity finding from step 2.

=== STEP 4 — Update section "3. Hotspots (churn × complexity)" ===
\`\`\`
Window: last 12 months · files with history: <N>
| # | File | Commits | Complexity (cog/cyc/LOC) | Score |
|---|---|---|---|---|
| 1 | src/orchestrator/index.ts | 87 | 142 (cognitive) | 0.83 |
| ... | | | | |

Method: churn × complexity (Tornhill). Hotspots are where refactoring pays —
they concentrate both change effort and defect risk.
\`\`\`

=== Cleanup ===
Delete \`./.huu/audits/.tmp/quality/churn.txt\` after writing the section.

=== HARD RULES ===
- DO NOT modify source code.
- Read-only git commands (\`git log\`) only — no checkouts, no resets.`;

const STEP4_PROMPT = `You are at step 4 — duplication scan (whole-project). Goal: find duplicated code blocks across the codebase, append findings to \`.huu/audits/quality-faq.json\`, populate section "4. Duplication" of \`.huu/audits/quality.md\`. NO code changes.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: a duplication involving a HOTSPOT file (step 3 findings) deserves a severity bump and a cross-reference in your "knowledge" field.

=== STEP 1 — Pick the tool ===
- If \`jscpd\` is available: \`npx --yes jscpd --min-lines 8 --min-tokens 50 --reporters json --output ./.huu/audits/.tmp/quality/jscpd-report .\` (defaults: min-tokens 50, min-lines 5 — we raise lines to 8 to cut noise). Read the JSON report.
- If \`pmd\` is available: \`pmd cpd --minimum-tokens 50 --files <src> --format text\`.
- Fallback: a fingerprint heuristic — hash sliding 10-line windows (normalized: collapse whitespace, strip comments) across all source files; report any hash collision as a duplication candidate.

=== STEP 2 — For each duplication >= 8 lines ===
Append:
\`\`\`json
{ "summary": "Duplication: <fileA>:Lx-Ly ~ <fileB>:Lx-Ly (<N> lines)", "knowledge": "<the duplicated snippet, redacted to 200 chars, plus a hint about which Fowler refactoring applies (Extract Function, Pull Up Method, etc.)>", "path": "<fileA>", "category": "duplication", "severity": "warn", "metric": { "name": "duplicate_lines", "value": <N> } }
\`\`\`

Severity: warn unless duplication > 50 lines (critical).

=== STEP 3 — Compute project-wide duplication percentage ===
Approximate: (duplicated lines) / (total source LOC). If >= 3% → write a critical summary finding under category "duplication" (3% is SonarQube's "Sonar way" quality-gate threshold for duplicated lines on new code).

=== STEP 4 — Update .huu/audits/quality.md section "4. Duplication" ===
Replace the placeholder with:

\`\`\`
Total source LOC: <N>
Duplicated LOC: <M>
Duplication %: <X>%
Threshold: 3% (Sonar way quality gate)
Top 10 duplications:
| Pair | Lines | Suggested refactoring |
|---|---|---|
| src/foo.ts:42-67 ↔ src/bar.ts:88-113 | 25 | Extract Function (https://refactoring.com/catalog/extractFunction.html) |
| ... | | |
\`\`\`

=== Cleanup ===
Delete \`./.huu/audits/.tmp/quality/jscpd-report\` (working artifact) if it was created.

=== HARD RULES ===
- DO NOT modify source code.
- DO NOT install additional tools at this step (step 1 already tried).
- Update ONLY section "4" of \`.huu/audits/quality.md\`.`;

const STEP5_PROMPT = `You are at step 5 — dead-code detection (whole-project). Goal: list unused exports, unused dependencies, unused private helpers. Append findings, populate section "5. Dead code" of \`.huu/audits/quality.md\`. NO code changes.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: dead code inside a file already flagged as a hotspot or complexity offender (steps 2–3) is the cheapest win — mark those entries "priority": 1, "fixability": "trivial".

=== STEP 1 — Pick tools per stack ===
- TS/JS:
  - \`npx --yes ts-unused-exports tsconfig.json\` if tsconfig present.
  - \`npx --yes depcheck\` for unused dependencies (npm packages).
  - \`npx --yes knip --reporter json\` if installable (catches all: deps, exports, files).
- Python: \`vulture <pkg-dir> --min-confidence 80\`.
- Go: \`go vet ./...\` + \`staticcheck -checks U1000 ./...\` if available.
- Rust: \`cargo udeps\` if installed; \`cargo clippy -- -W dead_code\`.
- Fallback: grep for exported symbols that have ZERO references in the rest of the codebase (cheap proxy).

=== STEP 2 — For each dead-code finding ===
\`\`\`json
{ "summary": "Unused export <symbol> in <file>", "knowledge": "<which tool found it, confidence, any context>", "path": "<file>", "category": "dead-code", "severity": "warn|info", "metric": { "name": "unused", "value": 1 } }
\`\`\`

Severity:
- warn: exported symbol with zero references inside the repo.
- info: unused dependency in package.json / requirements.txt / Cargo.toml.
- critical: rarely used — reserved for cases like the entire \`src/legacy/\` folder being dead.

=== STEP 3 — Update .huu/audits/quality.md section "5. Dead code" ===
Replace the placeholder with a table of the top 30 findings.

=== HARD RULES ===
- DO NOT delete anything. This is detection only.
- DO NOT update package.json's deps even if depcheck found unused ones.
- DO NOT touch source code.`;

const STEP6_PROMPT = `You are at step 6 — consolidation. Goal: read all findings from \`.huu/audits/quality-faq.json\`, compute a composite quality score, populate sections "6. Composite score" and "7. Recommendations" of \`.huu/audits/quality.md\`. Report-only — README is never touched.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/quality.md\` (sections 1–5 already populated).
- \`./.huu/audits/quality-faq.json\` (all findings).

=== STEP 2 — Compute composite quality score (0-100) ===
Start at 100. Subtract per finding:
- critical: -5 each (cap at -50 total).
- warn: -1 each (cap at -30 total).
- info: 0.

Score floor: 0. The table counts MUST match the FAQ entries exactly — the validation judge recounts them.

Per-file ranking: hotspot score (step 3) FIRST, then sum of severity weights (critical=5, warn=1). A high-churn complex file outranks an untouched complex file — that is the point of the hotspot method.

=== STEP 3 — Update .huu/audits/quality.md section "6. Composite score" ===
Replace the placeholder with:

\`\`\`
Composite quality score: <N>/100
Grade: <A: 90+, B: 75-89, C: 60-74, D: 40-59, F: <40>

Findings by category:
- Complexity: <count> (critical: <X>, warn: <Y>)
- Hotspots: <count>
- Duplication: <count>
- Dead code: <count>
- Size: <count>

Refactor-first list (hotspot-weighted, top 10):
| File | Hotspot score | Critical | Warn | Why first |
|---|---|---|---|---|
| src/orchestrator/runner.ts | 0.83 | 3 | 7 | high churn × high cognitive complexity |
| ... | | | | |
\`\`\`

=== STEP 4 — Update .huu/audits/quality.md section "7. Recommendations" ===
Group findings and write actionable recommendations, each linked to a Fowler refactoring catalog entry where applicable (https://refactoring.com/catalog/).
${KNOWLEDGE_ORDERING_NOTE}

### Critical (fix first)
- "src/foo.ts:bar() has cognitive 34 — apply Extract Function (https://refactoring.com/catalog/extractFunction.html) and Decompose Conditional; it is also the #2 hotspot (61 commits/12mo)."

### Warnings
- "src/baz.ts:42 ↔ src/qux.ts:88 — 30 line duplication. Extract a shared helper."

### Improvements
- "10 unused exports in src/utils/ — verify with a grep and remove if truly dead."

=== HARD RULES ===
- DO NOT modify any production file. The only output is \`.huu/audits/quality.md\`.
- DO NOT change findings retroactively in the FAQ (append-only).
- If you computed a composite score, mention it as a markdown line in the report itself (e.g. "Composite quality score: 76/100"). Do NOT add a README badge — the user can paste one manually if desired.`;

const STEP8_PROMPT = `You are the final agent — step 8 (post-validation). The judge approved the report. Goal: stamp section "8. Validation" of \`.huu/audits/quality.md\` and leave the working tree clean.

=== STEP 1 — Stamp the validation section ===
Replace the "## 8. Validation" placeholder with:
\`\`\`
Validated: <UTC timestamp> · findings: <total> (critical <X> / warn <Y> / info <Z>) · composite score <N>/100 · sections 1–7 complete.
Validation gate: judge CheckStep ("approved" required to reach this step; "rework" loops back to consolidation, max 2 judge runs).
\`\`\`
Numbers MUST come from re-reading \`.huu/audits/quality-faq.json\` and the report — do not invent them. Be idempotent: if the section is already stamped (a rework loop ran twice), overwrite it with fresh numbers.

=== STEP 2 — Exit hygiene ===
- Delete any leftovers under \`./.huu/audits/.tmp/quality/\` (keep the directory).
- Confirm \`git status --porcelain\` shows changes only under \`.huu/\` (plus at most the permitted \`.gitignore\` adjustment).

=== HARD RULES ===
- DO NOT modify the findings or the recommendations — stamp only.
- DO NOT touch production files.`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    description:
      'Sonar-style report: cyclomatic + cognitive complexity, size metrics, churn×complexity hotspots, duplication and dead code, rolled into a hotspot-weighted score. Report-only.',
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Detect stack, install tools, scaffold .huu/audits/quality.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Select complexity-scan targets',
        prompt: STEP_RECON_PROMPT,
        files: [],
        scope: 'project',
        // huu appends the huu-memory-v1 MEMORY CONTRACT (path + format + cap).
        produces: QUALITY_TARGETS_PATH,
      },
      {
        type: 'work',
        name: '3. Per-file complexity scan: $file',
        prompt: STEP2_PROMPT,
        files: [],
        // Autonomous file set from the recon step — no per-file picker.
        scope: 'memory',
        filesFrom: QUALITY_TARGETS_PATH,
        maxFiles: QUALITY_TARGETS_MAX_FILES,
      },
      {
        type: 'work',
        name: '4. Hotspot analysis (churn × complexity)',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. Project-wide duplication scan',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '6. Dead-code detection',
        prompt: STEP5_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '7. Composite score + recommendations',
        prompt: STEP6_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'check',
        name: '8. Validate report',
        condition: reportJudgeCondition({
          reportPath: '.huu/audits/quality.md',
          faqPath: '.huu/audits/quality-faq.json',
          requiredSections: [
            '1. Project stats',
            '2. Complexity findings',
            '3. Hotspots (churn × complexity)',
            '4. Duplication',
            '5. Dead code',
            '6. Composite score',
            '7. Recommendations',
          ],
          extraClauses: [
            'the composite score in section 6 is arithmetically consistent with the FAQ severity counts under the documented formula (100 − 5×critical capped at −50 − 1×warn capped at −30, floor 0).',
          ],
        }),
        maxRuns: 2,
        outcomes: [
          { label: 'approved', nextStepName: '9. Finalize report', default: true },
          { label: 'rework', nextStepName: '7. Composite score + recommendations' },
        ],
      },
      {
        type: 'work',
        name: '9. Finalize report',
        prompt: STEP8_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
