// Documentation-audit pipeline. Classifies docs by the Diátaxis framework
// (Tutorials / How-To / Reference / Explanation), scores README quality
// against the Awesome-README rubric, and flags stale or contradictory docs.
// REPORT-ONLY — no code changes.
//
// IMPORTANT: keep this file pure (no fs / no env). Imported on the hot path
// of `App` mount via the default-pipelines registry.

import type { Pipeline } from '../types.js';

export const DEFAULT_PIPELINE_FILENAME = 'huu-docs-audit.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Docs Audit';

const STEP1_PROMPT = `You are huu's documentation-audit bootstrap agent. Goal: enumerate every documentation artifact in the repo, write \`huu-docs.md\` at the root with the audit scaffold, and initialize \`huu-docs-faq.json\` as the per-file finding store.

=== STEP 1 — Enumerate documentation ===
Find every file that is documentation. Cast a wide net:
- README*, CHANGELOG*, CONTRIBUTING*, CODE_OF_CONDUCT*, SECURITY*, LICENSE* at the repo root.
- \`docs/\`, \`doc/\`, \`documentation/\`, \`site/\` recursively.
- \`*.md\`, \`*.mdx\`, \`*.rst\`, \`*.adoc\`, \`*.txt\` anywhere under the repo (excluding \`node_modules\`, \`dist\`, \`build\`, \`.git\`, \`vendor\`, \`target\`, \`__pycache__\`).
- Inline API docs: count of files with JSDoc (\`/** */\`), TSDoc, Python docstrings (\`"""..."""\`), Rustdoc (\`///\`), Javadoc.

Write the list to \`./huu-docs-files.txt\` (one path per line, sorted). This is a working file — step 6 may delete it at the end.

=== STEP 2 — Detect canonical files ===
Note presence/absence of:
- README at repo root (any case).
- CHANGELOG.
- CONTRIBUTING.
- LICENSE.
- CODE_OF_CONDUCT.
- SECURITY.
- A docs directory (\`docs/\`).

=== STEP 3 — Write huu-docs.md scaffold AT THE ROOT ===
Path: \`./huu-docs.md\`. Required structure (English, no fluff):

# huu-docs.md — Documentation audit

> Audit generated by huu's Docs Audit pipeline. Report-only — no source code was modified.

## 1. Inventory
- Total doc files: <N>
- Markdown / RST / AsciiDoc breakdown: <numbers>
- Canonical files present: README=<yes/no>, CHANGELOG=<yes/no>, CONTRIBUTING=<yes/no>, LICENSE=<yes/no>, CODE_OF_CONDUCT=<yes/no>, SECURITY=<yes/no>
- Inline API doc coverage estimate: <N public exports / N documented> (filled in by step 5)

## 2. Diátaxis classification
(filled in by step 2 of the audit)

## 3. README scorecard
(filled in by step 3 of the audit)

## 4. Staleness scan
(filled in by step 4)

## 5. API doc coverage
(filled in by step 5)

## 6. Recommendations
(filled in by step 6)

=== STEP 4 — Initialize huu-docs-faq.json ===
Path: \`./huu-docs-faq.json\`.
If absent: write \`[]\` + trailing newline.
If present and a valid array: leave untouched.
If present and corrupted: replace with \`[]\` and note in commit message.

Schema per entry (appended by later steps):
\`\`\`json
{ "summary": "<=256 chars", "knowledge": "<=5000 chars", "path": "<doc file>", "category": "diataxis|readme|staleness|api-doc|recommendation", "severity": "info|warn|critical" }
\`\`\`

=== HARD RULES ===
- No source-code changes outside the new files above + \`huu-docs-files.txt\`.
- DO NOT delete or move existing docs in this step.
- Be language-agnostic — do not assume Node.js.`;

const STEP2_PROMPT = `You are at step 2 — Diátaxis classification. Goal: classify every doc enumerated in \`huu-docs-files.txt\` against the Diátaxis quadrants, append findings to \`huu-docs-faq.json\`, and populate section "2. Diátaxis classification" of \`huu-docs.md\`.

=== Diátaxis primer (https://diataxis.fr/) ===
Four orthogonal documentation kinds:
- **Tutorial** — learning-oriented; guides a beginner through doing something, hand-held; focus on the user's skill development.
- **How-To Guide** — task-oriented; addresses a real-world problem for a competent user; focus on the goal, not the learning.
- **Reference** — information-oriented; neutral, structured, mirrors the architecture of the thing described (API specs, CLI flags, config schemas).
- **Explanation** — understanding-oriented; context, background, "why" decisions were made (ADRs, architecture overviews, design rationale).

Plus a fifth bucket:
- **Unclassified** — doesn't fit cleanly; could be a mix or marketing.

=== STEP 1 — Read inputs ===
- \`./huu-docs-files.txt\` (built in step 1).
- \`./huu-docs.md\` (scaffold).
- \`./huu-docs-faq.json\` (may be empty).

If any are missing: abort with a clear error.

=== STEP 2 — Classify each doc ===
For each file:
1. Read the first ~200 lines (enough to identify the genre).
2. Decide ONE primary classification: tutorial / how-to / reference / explanation / unclassified.
3. Score quality 0–10 against its category's expectations:
   - Tutorial: starts with a concrete goal, hand-holds, has no detours, gives a real result.
   - How-To: lists prerequisites, gives ordered steps, no fluff.
   - Reference: complete coverage of the thing described, neutral tone, structured.
   - Explanation: explains "why", not "how"; links to references and how-tos rather than inlining them.
4. APPEND to \`huu-docs-faq.json\`:
   \`\`\`json
   { "summary": "<one-line summary of the doc>", "knowledge": "<why this classification, what's weak, what's strong>", "path": "<file>", "category": "diataxis", "severity": "<info|warn|critical>" }
   \`\`\`
   Severity heuristic: info = clearly fits a quadrant and is decent; warn = misclassified or low quality; critical = the file claims to be one type but is mostly another (the most damaging anti-pattern per Diátaxis).

=== STEP 3 — Update huu-docs.md section "2. Diátaxis classification" ===
Replace the placeholder with a markdown table:

| File | Type | Score (0-10) | Notes |
|---|---|---|---|
| README.md | reference | 5 | mixes tutorial and reference (anti-pattern) |
| docs/getting-started.md | tutorial | 8 | strong |
| ... | | | |

Plus a summary block:
\`\`\`
Tutorials: X
How-to: X
Reference: X
Explanation: X
Unclassified: X
Diátaxis anti-patterns flagged: X (see findings in huu-docs-faq.json)
\`\`\`

=== HARD RULES ===
- Append-only to \`huu-docs-faq.json\` — never rewrite from scratch.
- Re-read the FAQ file before each append (parallel agents may have appended too).
- Update ONLY section "2" of \`huu-docs.md\` — leave the other sections untouched.
- DO NOT modify the docs themselves.`;

const STEP3_PROMPT = `You are at step 3 — README quality scorecard. Goal: score the project's README against the Awesome-README rubric (https://github.com/matiassingers/awesome-readme), append findings, and populate section "3. README scorecard" of \`huu-docs.md\`.

=== STEP 1 — Locate the README ===
Search case-insensitively for \`README*\` at the repo root. If multiple (e.g. README.md + README.es.md), score the English one if present; otherwise the largest by byte size. If NO README exists, write the scorecard with all checks failing and severity=critical.

=== STEP 2 — Rubric (10 checks, 10 pts each — score out of 100) ===
For each, give 10 if present and well-done, 5 if present but weak, 0 if absent.

1. **Title** — clear project name as an H1.
2. **One-line description** — a single concise sentence under the title that answers "what is this".
3. **Badges** — at least one (build/version/coverage/license) near the top.
4. **Visual demo** — screenshot, GIF, ASCII art, or diagram showing the product in action.
5. **Installation** — a copy-pasteable install/setup section.
6. **Usage / examples** — at least one real, runnable example (not a stub).
7. **Features** — bulleted list of key capabilities.
8. **Documentation links** — links to further docs (tutorials, API, etc.).
9. **Contributing** — a section or link explaining how to contribute.
10. **License** — explicit license mention near the bottom.

Total score → 0–100. Color grade:
- >= 80 → \`green\`
- 50–79 → \`yellow\`
- < 50 → \`red\`

=== STEP 3 — Append finding ===
\`\`\`json
{ "summary": "README scorecard: <N>/100", "knowledge": "<itemized breakdown of which checks passed/failed and why>", "path": "<readme path or 'none'>", "category": "readme", "severity": "<info if >=80, warn if 50-79, critical if <50>" }
\`\`\`

=== STEP 4 — Update huu-docs.md section "3. README scorecard" ===
Replace the placeholder with:

| Check | Score | Notes |
|---|---|---|
| Title | 10/10 | Clear H1 |
| One-line description | 5/10 | Vague |
| Badges | 0/10 | None |
| ... | | |
| **Total** | **<N>/100** | grade: <green/yellow/red> |

=== HARD RULES ===
- Append-only to \`huu-docs-faq.json\`.
- DO NOT modify the README itself.
- Update ONLY section "3" of \`huu-docs.md\`.`;

const STEP4_PROMPT = `You are at step 4 — staleness scan. Goal: detect docs that reference removed files, contradict current code, or have not been touched in > 12 months. Append findings and populate section "4. Staleness scan" of \`huu-docs.md\`.

=== STEP 1 — Build a list of doc files to scan ===
Use \`huu-docs-files.txt\` from step 1. If absent: re-enumerate (same heuristic).

=== STEP 2 — For each doc file, run three checks ===

**Check A — Dead references**
Extract every code-style reference: backtick'd file paths, code-block paths, links like \`[name](relative/path)\`, and command names. For each:
- If it looks like a repo file path (\`src/...\`, \`./...\`, \`../...\`, \`packages/...\`): test \`test -e <path>\`. If missing → finding (severity warn).
- If it looks like a CLI command (\`npm run X\`, \`make X\`, \`pnpm X\`): check the project's manifest for that script. If missing → finding (severity warn).
- If it's an external URL: skip (network out of scope here).

**Check B — Code contradiction**
For docs that include CLI snippets in fenced code blocks, sample-check 3–5 commands at random. Heuristic test: does the command's binary exist in the project / on PATH? E.g. doc says \`npm run dev\` but only \`npm start\` is defined.

**Check C — Age (last commit touching the file)**
Use git: \`git log -1 --format=%at -- <path>\`. If the timestamp is older than 365 days, that's an age finding (severity info; warn only if the file also appears stale by checks A/B).

=== STEP 3 — Append findings ===
For EACH finding from any of the three checks:
\`\`\`json
{ "summary": "<one-line: e.g. 'docs/setup.md references missing src/legacy/db.ts'>", "knowledge": "<full context: which line of the doc, what the reference was, what's actually there now>", "path": "<doc path>", "category": "staleness", "severity": "info|warn|critical" }
\`\`\`

Severity:
- critical: doc contradicts current code in a way that would actively mislead a user (e.g. install instructions point to a removed file).
- warn: dead reference or contradiction that's unlikely to actively break anyone, but is wrong.
- info: just age.

=== STEP 4 — Update huu-docs.md section "4. Staleness scan" ===
Replace the placeholder with a table:

| Doc | Finding | Severity | Notes |
|---|---|---|---|

Plus summary counts (critical/warn/info).

=== HARD RULES ===
- Append-only to \`huu-docs-faq.json\`.
- DO NOT modify the docs.
- DO NOT modify code referenced by the docs.`;

const STEP5_PROMPT = `You are at step 5 — API doc coverage for \`$file\`. Goal: for this ONE source file, list its public exports and check whether each has an inline doc-comment (JSDoc / TSDoc / docstring / Rustdoc / Javadoc).

=== STEP 1 — Read \`$file\` and identify language ===
Use the extension and content to determine which doc-comment style applies:
- TypeScript / JavaScript: JSDoc / TSDoc (\`/** */\` above the export).
- Python: triple-quoted docstring as the first statement of the function/class.
- Rust: \`///\` or \`/** */\` above the item.
- Go: \`//\` line(s) directly above the exported identifier (idiomatic Go doc style).
- Java / Kotlin: Javadoc / KDoc (\`/** */\` above the method/class).
- Ruby: \`#\` lines above the method.
- C / C++: Doxygen \`/** */\` or \`/// \` above the declaration.

If the language isn't detected, finish silently with no findings.

=== STEP 2 — Enumerate public exports ===
Per language:
- TypeScript: any \`export\` (named/default), top-level functions/classes/interfaces. Skip internal helpers (those prefixed with \`_\`).
- Python: top-level \`def\` / \`class\` (skip names starting with \`_\`).
- Rust: items marked \`pub\` / \`pub(crate)\`.
- Go: identifiers that start with an uppercase letter at package level.
- Java: \`public\` methods/classes.

=== STEP 3 — Check doc presence per export ===
For each export:
- Is there an immediately-adjacent doc-comment of the right style? Yes/no.
- If yes, does it have at least one sentence of substance (not just \`/** Foo */\` re-stating the name)?

=== STEP 4 — Append ONE finding per file ===
\`\`\`json
{ "summary": "$file: <documented>/<total> public exports have substantive docs", "knowledge": "<list of undocumented exports + 1-line note per missing doc>", "path": "$file", "category": "api-doc", "severity": "info|warn|critical" }
\`\`\`

Severity:
- info: 100% documented.
- warn: >= 50% documented.
- critical: < 50% of public exports documented.

=== HARD RULES ===
- ONLY analyze \`$file\` — do not touch other files.
- DO NOT modify \`$file\`.
- Append-only to \`huu-docs-faq.json\` (re-read before appending — other agents are running in parallel).`;

const STEP6_PROMPT = `You are the final agent — step 6. Goal: consolidate findings from \`huu-docs-faq.json\` into the "5. API doc coverage" and "6. Recommendations" sections of \`huu-docs.md\`, and clean up working files.

=== STEP 1 — Read inputs ===
- \`./huu-docs.md\` (sections 1–4 already populated).
- \`./huu-docs-faq.json\` (all findings).

=== STEP 2 — Compute API doc coverage section "5" ===
Aggregate findings with \`category: "api-doc"\`:
- Total public exports across all files = sum of "total" values from findings.
- Total documented = sum of "documented" values.
- Per-file table sorted by undocumented count descending (top 20).

Write into section "5. API doc coverage":

\`\`\`
Total public exports: <N>
Documented: <M> (<percentage>%)
Files with critical gaps (< 50% docs):
| File | Documented / Total | Severity |
|---|---|---|
| src/foo.ts | 3/12 | critical |
| ... | | |
\`\`\`

=== STEP 3 — Compute section "6. Recommendations" ===
Synthesize from ALL findings into prioritized recommendations:

### Critical (do these first)
- Bullet for each critical-severity finding, grouped by category. Include the path and a 1-line action.

### Warnings (do these next)
- Same format for warn findings.

### Diátaxis gaps
- Quadrants that have 0 or near-0 docs → recommend creating at least one doc in each missing quadrant.
- Files flagged as misclassified (warn/critical under category "diataxis") → recommend splitting them per Diátaxis.

### Suggested next steps (template)
- "Add a Tutorial: docs/tutorials/quickstart.md — walks a first-time user through running the project end-to-end."
- "Add a Reference: docs/reference/cli.md — exhaustive flag-by-flag table for the CLI."
- "Add an Explanation: docs/explanation/architecture.md — why the layered design and how the pieces fit."

=== STEP 4 — Clean up ===
- Delete \`./huu-docs-files.txt\` (working file).
- Keep \`huu-docs.md\` and \`huu-docs-faq.json\`.

=== HARD RULES ===
- DO NOT modify any docs other than \`huu-docs.md\` itself.
- DO NOT modify source code.
- Final \`huu-docs.md\` should be a complete, self-contained report a human can read top-to-bottom.`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Enumerate docs and scaffold huu-docs.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Diataxis classification',
        prompt: STEP2_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '3. README quality scorecard',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '4. Staleness scan',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. API doc coverage for $file',
        prompt: STEP5_PROMPT,
        files: [],
        scope: 'per-file',
      },
      {
        type: 'work',
        name: '6. Consolidate report and cleanup',
        prompt: STEP6_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
