// Performance-audit pipeline. Static hotspot detection (N+1, big-O, sync I/O,
// memory leak signals, unbounded concurrency, missing caching) + frontend
// Core Web Vitals (if applicable) + USE method checklist for backend/CLI
// projects. REPORT-ONLY. A judge CheckStep validates the report.
//
// Methodologies:
// - Brendan Gregg USE method: https://www.brendangregg.com/usemethod.html
// - Google Core Web Vitals (p75, mobile/desktop): LCP <=2.5s, INP <=200ms
//   (replaced FID in March 2024), CLS <=0.1. https://web.dev/articles/vitals
//   Lab caveat: Lighthouse cannot measure INP — TBT is the lab proxy.
// - Azure Architecture performance antipatterns (chatty I/O, no caching,
//   improper instantiation): https://learn.microsoft.com/en-us/azure/architecture/antipatterns/

import type { Pipeline } from '../types.js';
import {
  knowledgeProtocol,
  persistenceCheck,
  reportJudgeCondition,
  targetsRecon,
  KNOWLEDGE_OPTIONAL_FIELDS_NOTE,
  KNOWLEDGE_ORDERING_NOTE,
} from './knowledge-protocol.js';

const PERF_TARGETS_PATH = '.huu/audits/performance-targets.json';
const PERF_TARGETS_MAX_FILES = 30;

export const DEFAULT_PIPELINE_FILENAME = 'huu-performance-audit.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Performance Audit';

const FAQ_PATH = './.huu/audits/performance-faq.json';
const FAQ_SCHEMA_LINE =
  '{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file or \'global\'>", "category": "n+1|big-o|sync-io|memory|render-blocking|use-method|cwv|bundle", "severity": "info|warn|critical", "metric": { "name": "...", "value": ... } }';

const STEP1_PROMPT = `You are huu's performance-audit bootstrap agent. Goal: classify the project (frontend / backend / library / CLI / mobile), make ephemeral profilers available, write \`.huu/audits/performance.md\` scaffold, initialize \`.huu/audits/performance-faq.json\`.

=== STEP 0 — REPORT-ONLY HARD RULE ===
You may NOT modify any file in the repo OTHER than the audit artifacts under \`.huu/audits/\` (and \`.huu/audits/.tmp/\` for working files) plus the single \`.gitignore\` adjustment described below. If a tool requires installation, use \`npx --yes <tool>\` (Node), \`pipx run <tool>\` (Python), or vendored binaries under \`$HOME/.huu/bin/\`. NEVER touch package.json, requirements.txt, pyproject.toml, Cargo.toml, go.mod, lockfiles, or any production source. Create the output directory with \`mkdir -p .huu/audits/.tmp/performance\` before writing.

${persistenceCheck('audits')}

=== STEP 1 — Classify the project ===
Inspect the manifests and pick the BEST single classification (or "mixed"):
- **frontend**: package.json has react/vue/svelte/next/nuxt/angular, plus an entry like \`vite\`/\`webpack\`/\`next\` config. Public assets folder.
- **backend**: package.json has express/fastify/koa/hapi/nestjs OR pyproject.toml has flask/fastapi/django OR go.mod with web framework OR Java with Spring etc.
- **cli**: package.json bin field, or a Python entrypoint, or Go/Rust binary target without web routes.
- **library**: exports a public API, no bin/entry server, package.json has \`main\`/\`exports\`/\`types\`.
- **mobile**: react-native, Flutter (pubspec.yaml), Android (build.gradle), iOS (.xcodeproj).
- **mixed**: doesn't fit one clearly (e.g. monorepo).

Note the classification — subsequent steps key off it.

=== STEP 2 — Make profilers available (ephemeral only) ===
EPHEMERAL ONLY. Use one-shot runners that DON'T modify the repo's manifests:

**frontend**
- \`npx --yes @lhci/cli@latest collect <args>\` (Lighthouse CI for Core Web Vitals).
- \`npx --yes source-map-explorer <args>\` for bundle weight.
- \`npx --yes vite-bundle-visualizer <args>\` for Vite projects.

**backend (Node)**
- \`npx --yes clinic <args>\` (clinic.js).
- \`npx --yes autocannon <url>\` (load gen — DO NOT add to devDeps).

**backend (Python)**
- \`pipx run py-spy <args>\`.
- \`pipx run scalene <args>\`.

**Go**
- Install pprof to ephemeral bin: \`GOBIN=$HOME/.huu/bin go install github.com/google/pprof@latest\`. NEVER add to the project.

**Rust**
- Use \`cargo clippy\` if already configured. Skip flamegraph if not (heavy install).

If a tool is not reachable: append an info finding and continue. The pipeline NEVER hard-fails on missing tools.

=== STEP 3 — Write .huu/audits/performance.md scaffold ===
Path: \`./.huu/audits/performance.md\`. Required structure:

# .huu/audits/performance.md — Performance audit

> Report-only static performance audit generated by huu's Performance Audit pipeline.

## 1. Classification
- Project type: <frontend|backend|cli|library|mobile|mixed>
- Languages: <list>
- Available profilers: <list>
- Unavailable profilers: <list with reason>

## 2. Static hotspot scan
(filled in by the per-file hotspot scan)

## 3. Frontend metrics (Core Web Vitals)
(filled in by step 3 — only if classification = frontend or mixed)

## 4. USE checklist (Brendan Gregg)
(filled in by step 4 — only if classification = backend / cli / mixed)

## 5. Bundle / artifact weight
(filled in by step 4 — frontend & library)

## 6. Recommendations
(filled in by step 5)

## 7. Validation
(filled in by the final step after the judge approves)

=== STEP 4 — Initialize .huu/audits/performance-faq.json ===
\`./.huu/audits/performance-faq.json\`. Standard idempotency rules. Schema:
\`\`\`json
{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file or 'global'>", "category": "n+1|big-o|sync-io|memory|render-blocking|use-method|cwv|bundle", "severity": "info|warn|critical", "metric": { "name": "...", "value": ... } }
\`\`\`
${KNOWLEDGE_OPTIONAL_FIELDS_NOTE}

=== HARD RULES ===
- DO NOT modify source code.
- DO NOT run benchmarks against external services or production.
- Tool installs only — no other changes outside the new artifacts.`;

const STEP_RECON_PROMPT = `${targetsRecon({
  role: "huu's performance-hotspot target selector",
  purpose: 'scanning for static performance hotspots in',
  prefer: [
    'hot paths — request/event handlers, loops over collections, DB/ORM access, data transforms, serialization',
    'files doing synchronous I/O, heavy computation, or unbounded concurrency',
    'render-critical frontend components and anything on the startup / request critical path',
  ],
  hintGuide:
    'name the suspected hotspot (N+1 query, nested loop / big-O, sync I/O, memory leak, render-blocking)',
  maxFiles: PERF_TARGETS_MAX_FILES,
})}

=== BEFORE YOU START ===
Read \`./.huu/audits/performance.md\` section 1 (the scaffold step recorded the project classification — frontend / backend / library / CLI / mobile / mixed). Lean toward the files that classification makes risky (frontend → render-critical components; backend → request handlers and DB access). This step writes ONLY the target list; the per-file hotspot scan that follows does the actual finding.`;

const STEP2_PROMPT = `You are the static hotspot scan for ONE file: \`$file\`. You are one of many agents running in parallel; your whole job is this single file. Goal: identify likely performance hotspots in this single file and append findings to \`.huu/audits/performance-faq.json\`. NO code changes.

The recon step chose this file deliberately and left you a lead — start there: $hint

=== STEP 0 — SKIP RULE ===
SKIP IMMEDIATELY (no findings, no FAQ append) if \`$file\` matches: \`node_modules/\`, \`dist/\`, \`build/\`, \`out/\`, \`coverage/\`, \`.git/\`, \`vendor/\`, \`target/\`, \`__pycache__/\`, \`*.generated.*\`, \`*.min.js\`, \`*.min.css\`, \`*.d.ts\`, \`*.lock\`, \`*.snap\`.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/performance.md\` (note the classification in section 1).
- \`./.huu/audits/performance-faq.json\` (may be empty).
- \`$file\`.

=== STEP 2 — Patterns to detect ===

**N+1 query patterns**
- Loop over collection, fetch related record inside loop:
  - JS/TS: \`for (const x of xs) { await fetch(\`/api/\${x.id}\`) }\`, \`xs.forEach(async x => { await db.find(...) })\`, ORM patterns: \`users.forEach(u => u.posts)\` without eager load.
  - Python (Django/SQLAlchemy): \`for u in users: u.posts\` without \`prefetch_related\`/\`selectinload\`.
  - Ruby (ActiveRecord): \`users.each { |u| u.posts }\` without \`includes\`.
- Severity: warn unless inside a public HTTP handler / endpoint route → critical.

**O(n²)+ hotspots**
- Nested loops over user-controlled input (request body, query params, file contents).
- \`.find()\` / \`.indexOf()\` inside \`.map()\` / \`.filter()\` / \`.forEach()\` on the same collection.
- Severity: warn unless input size is unbounded → critical.

**Sync I/O in hot paths**
- \`readFileSync\`, \`writeFileSync\`, \`execSync\`, \`fs.statSync\` inside an HTTP handler / event loop tick.
- Blocking sleep in async code (\`await new Promise(r => setTimeout(r, ms))\` is OK; \`spinLoop\` is not).
- Python: synchronous \`requests.get\` inside an \`async def\` (a common bug).
- Severity: warn for utility code; critical for request-handling code.

**Memory leak signals**
- \`addEventListener\` without matching \`removeEventListener\` (also \`.on()\` without \`.off()\`).
- Global / module-level mutable collections that only grow.
- \`setInterval\` without \`clearInterval\` referenced in the same scope.
- Severity: warn.

**Render-blocking / bundle-bloat (frontend only)**
- Large \`import\` of an entire library where tree-shake is available (\`import * as lodash from 'lodash'\` vs \`import debounce from 'lodash/debounce'\`).
- Synchronous \`<script>\` tags in HTML head.
- \`require()\` calls inside React component bodies (forces re-evaluation on render).
- Severity: warn.

**Inefficient regex**
- \`(.+)+\`, \`(a*)*\`, catastrophic-backtracking shapes.
- Regex compilation inside a loop (move to module scope).
- Severity: warn unless on user input → critical.

**Unbounded concurrency** (Azure antipatterns: improper instantiation)
- \`Promise.all(items.map(...))\` over an unbounded/user-controlled list (no p-limit/chunking).
- A new client per request: \`new S3Client()\` / \`new PrismaClient()\` / \`http.Agent\` constructed inside a handler instead of module scope.
- Severity: warn; critical when the list size is user-controlled.

**Missing caching / extraneous fetching** (Azure antipatterns: no-caching, extraneous fetching)
- The same remote/DB fetch repeated with identical arguments inside one request lifecycle.
- \`SELECT *\` / full-collection fetches followed by in-memory filtering of a handful of fields; endpoints returning unbounded lists with no pagination.
- Severity: warn.

=== STEP 3 — Append findings ===
For EACH match found:
\`\`\`json
{ "summary": "$file: <line>: <pattern> (<short context>)", "knowledge": "<the offending code snippet, the rule it triggered, suggested fix in 1-2 sentences>", "path": "$file", "category": "n+1|big-o|sync-io|memory|render-blocking", "severity": "info|warn|critical" }
\`\`\`

If \`$file\` has zero findings, append ONE info-severity confirmation.

=== HARD RULES ===
- DO NOT modify \`$file\` or any other file.
- DO NOT run tests / benchmarks (this step is static analysis only).
- Append-only to the FAQ (re-read before each append; parallel agents).`;

const STEP3_PROMPT = `You are at step 3 — frontend Core Web Vitals. Goal: if the project classifies as a frontend, attempt to capture LCP / INP / CLS via lighthouse-ci (or a static heuristic if not). Append findings, populate section "3. Frontend metrics" of \`.huu/audits/performance.md\`. SKIP this step gracefully for non-frontend projects.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: step 2's per-file findings under "render-blocking" and "bundle" point at the files most likely to explain a bad LCP — cross-reference them in your "knowledge" field instead of re-discovering them.

=== STEP 1 — Check classification ===
Read \`./.huu/audits/performance.md\` section 1. If classification is NOT frontend or mixed: write "N/A — non-frontend project" into section "3. Frontend metrics" and finish.

=== STEP 2 — Build the app (best-effort) ===
Try common build commands in order:
- \`npm run build\`
- \`yarn build\`
- \`pnpm build\`
- \`vite build\`

If none works, skip to step 4 (static fallback).

=== STEP 3 — Run Lighthouse against the built bundle ===
If \`@lhci/cli\` was installed in step 1:
- Identify the dev/preview server command (\`npm run preview\`, \`npx serve dist\`, etc.).
- Start it in the background on a free port.
- Run: \`npx --yes lighthouse "http://localhost:<port>" --output=json --output-path=./.huu/audits/.tmp/performance/lighthouse.json --chrome-flags="--headless --no-sandbox --disable-gpu"\`.
- Parse the JSON to extract \`audits.largest-contentful-paint.numericValue\`, \`audits.total-blocking-time.numericValue\`, \`audits.cumulative-layout-shift.numericValue\`, \`audits.first-contentful-paint.numericValue\`.
- Stop the background server.

Targets (Google's published thresholds, assessed at the 75th percentile in the field, https://web.dev/articles/vitals):
- LCP: good <= 2500 ms, poor > 4000 ms.
- INP: good <= 200 ms, poor > 500 ms. **Lab caveat (web.dev): Lighthouse cannot measure INP (no real user input) — report Total Blocking Time (TBT) as the lab PROXY for INP (good <= 200 ms, poor > 600 ms) and say so explicitly in the scorecard. A real INP number requires field/RUM data (CrUX).**
- CLS: good <= 0.1, poor > 0.25.
- FCP: good <= 1800 ms, poor > 3000 ms.

=== STEP 4 — Static fallback (if Lighthouse couldn't run) ===
Identify potential bottlenecks WITHOUT running the app:
- Total JS bundle size from \`dist/\` / \`build/\` / \`.next/\` (warn > 200 KB gzipped, critical > 500 KB).
- Inline \`<script>\` tags in \`index.html\` (render-blocking).
- Number of font files in public/ (each adds RTT cost).
- Presence of \`loading="lazy"\` on \`<img>\` tags throughout the codebase.

=== STEP 5 — Append findings and update section "3" ===
For each metric outside the "good" band:
\`\`\`json
{ "summary": "LCP=3200ms (target <=2500ms)", "knowledge": "<full Lighthouse audit context or static heuristic>", "path": "global", "category": "cwv", "severity": "warn|critical", "metric": { "name": "lcp_ms", "value": 3200 } }
\`\`\`

Update section "3. Frontend metrics" in \`.huu/audits/performance.md\` with a scorecard table.

=== Cleanup ===
- Delete \`.huu-lighthouse.json\` and any temporary server-stop artifacts.
- Stop any background processes you started.

=== HARD RULES ===
- DO NOT modify the app's source code.
- DO NOT push or commit anything beyond the audit artifacts.
- If you couldn't run Lighthouse, that's fine — the static fallback is the report.`;

const STEP4_PROMPT = `You are at step 4 — USE checklist (backend / CLI) and bundle weight (frontend / library). Skip the irrelevant half based on classification.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: step 2's "sync-io" and "n+1" findings tell you which software resources (DB pool, event loop, worker queue) deserve a USE row — start the checklist from them.

=== STEP 1 — Branch on classification ===
Read \`./.huu/audits/performance.md\` section 1.
- If backend / cli / mixed → fill USE method checklist (section "4").
- If frontend / library / mixed → measure bundle/artifact weight (section "5").

Both can run for mixed projects.

=== STEP 2A — USE method checklist (Brendan Gregg, https://www.brendangregg.com/usemethod.html) ===
For each system resource the project actively uses, document the THREE columns: Utilization, Saturation, Errors. You are doing a STATIC pre-flight — actual measurement needs the running app. The goal is to identify WHICH metrics matter for this project and list the canonical commands to check them once it's running.

| Resource | Utilization | Saturation | Errors |
|---|---|---|---|
| CPU | top, mpstat -P ALL, htop | runqueue (vmstat r), load avg | mpstat -P (some platforms report ECC) |
| Memory | free, vmstat | si/so paging (vmstat), swap usage | dmesg \\| grep -i oom |
| Disk I/O | iostat -xz 1 | iostat avgqu-sz / aqu-sz, %util > 80% | dmesg \\| grep -i error |
| Network | sar -n DEV 1, ifconfig | netstat -s (overruns, drops), TCP retransmits | netstat -i (errors), \`ss -i\` |
| File descriptors | \`lsof -p <pid> \\| wc -l\` | rlimit close to \`ulimit -n\` | EMFILE in logs |
| Open connections | \`ss -tan\` | conn-tracker table size | TCP refused/reset metrics |

For SOFTWARE resources (project-specific):
- DB connection pool: usage vs max; "wait for connection" events.
- Worker thread pool / async queue: depth; rejected enqueues.
- Cache: hit rate; eviction rate; missing-on-write conflicts.

=== STEP 2B — Bundle / artifact weight (frontend / library) ===
- Frontend: total bundle size from \`dist/\` / \`build/\` / \`.next/\` / \`out/\`. Gzipped if possible.
- Library: published artifact size (\`npm pack --dry-run --json\`). Warn if > 100 KB unpacked.
- Compare against industry rules:
  - Frontend critical-path JS gzip: > 200 KB = warn, > 500 KB = critical.
  - Library unpackedSize: > 1 MB = warn, > 5 MB = critical.

=== STEP 3 — Append findings and update sections "4" and "5" ===
For each resource where a likely concern is identified (e.g. project uses a DB but has no connection-pool config), append a USE-method finding:
\`\`\`json
{ "summary": "DB pool size hardcoded to 10 — saturation risk under > 50 req/s", "knowledge": "<details, including the file + line>", "path": "<file>", "category": "use-method", "severity": "warn" }
\`\`\`

For bundle weight:
\`\`\`json
{ "summary": "dist/main.js = 720 KB gzip — exceeds 500 KB critical threshold", "knowledge": "<top-5 contributing modules from source-map-explorer if available, else 'install source-map-explorer for module-level breakdown'>", "path": "global", "category": "bundle", "severity": "critical", "metric": { "name": "bundle_gzip_kb", "value": 720 } }
\`\`\`

=== HARD RULES ===
- DO NOT modify source.
- DO NOT delete the bundle artifacts (the user may want to inspect them).`;

const STEP5_PROMPT = `You are the final agent — step 5. Goal: read all findings from \`.huu/audits/performance-faq.json\`, prioritize them, populate section "6. Recommendations" of \`.huu/audits/performance.md\`. No production-file edits.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/performance.md\` (sections 1–5 already populated).
- \`./.huu/audits/performance-faq.json\`.

=== STEP 2 — Compute composite perf score ===
Start at 100. Subtract per finding:
- critical: -8 (cap -50).
- warn: -2 (cap -30).
- info: 0.

The counts you cite MUST match the FAQ entries exactly — the validation judge recounts them.

=== STEP 3 — Populate section "6. Recommendations" ===
Group by category, prioritize by severity.
${KNOWLEDGE_ORDERING_NOTE}

### Critical hotspots
- Cite each by \`<file>:<line>\` and give a one-liner fix.

### Warnings
- Same format.

### Frontend-specific (if applicable)
- "LCP is 3.2s — investigate render-blocking JS in <head>."
- "Bundle is 720 KB gzip — code-split with React.lazy / dynamic import()."

### Backend / CLI-specific (if applicable)
- "Wire pool metrics → Grafana before going to prod."
- "Add an integration test that exercises the USE method's saturation row for DB connections."

=== HARD RULES ===
- DO NOT modify any production file. The only output is \`.huu/audits/performance.md\`.
- If you computed a composite score, mention it as a markdown line in the report itself. Do NOT add a README badge.
- DO NOT skip the report even if there are no critical findings — write "No critical findings — keep the audit alive in CI" recommendation.`;

const STEP7_PROMPT = `You are the final agent — step 7 (post-validation). The judge approved the report. Goal: stamp section "7. Validation" of \`.huu/audits/performance.md\` and leave the working tree clean.

=== STEP 1 — Stamp the validation section ===
Replace the "## 7. Validation" placeholder with:
\`\`\`
Validated: <UTC timestamp> · findings: <total> (critical <X> / warn <Y> / info <Z>) · composite score <N>/100 · sections 1–6 complete.
Lab metrics caveat preserved: INP reported via its lab proxy (TBT) when only Lighthouse data was available.
Validation gate: judge CheckStep ("approved" required to reach this step; "rework" loops back to consolidation, max 2 judge runs).
\`\`\`
Numbers MUST come from re-reading \`.huu/audits/performance-faq.json\` and the report — do not invent them. Be idempotent: if the section is already stamped (a rework loop ran twice), overwrite it with fresh numbers.

=== STEP 2 — Exit hygiene ===
- Delete any leftovers under \`./.huu/audits/.tmp/performance/\` (keep the directory).
- Confirm \`git status --porcelain\` shows changes only under \`.huu/\` (plus at most the permitted \`.gitignore\` adjustment).

=== HARD RULES ===
- DO NOT modify the findings or the recommendations — stamp only.
- DO NOT touch production files.`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Classify project, install profilers, scaffold .huu/audits/performance.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Select hotspot-scan targets',
        prompt: STEP_RECON_PROMPT,
        files: [],
        scope: 'project',
        // huu appends the huu-memory-v1 MEMORY CONTRACT (path + format + cap).
        produces: PERF_TARGETS_PATH,
      },
      {
        type: 'work',
        name: '3. Static hotspot scan: $file',
        prompt: STEP2_PROMPT,
        files: [],
        // Autonomous file set from the recon step — no per-file picker.
        scope: 'memory',
        filesFrom: PERF_TARGETS_PATH,
        maxFiles: PERF_TARGETS_MAX_FILES,
      },
      {
        type: 'work',
        name: '4. Frontend Core Web Vitals',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. USE checklist + bundle weight',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '6. Composite score + recommendations',
        prompt: STEP5_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'check',
        name: '7. Validate report',
        condition: reportJudgeCondition({
          reportPath: '.huu/audits/performance.md',
          faqPath: '.huu/audits/performance-faq.json',
          requiredSections: [
            '1. Classification',
            '2. Static hotspot scan',
            '3. Frontend metrics (Core Web Vitals)',
            '4. USE checklist (Brendan Gregg)',
            '5. Bundle / artifact weight',
            '6. Recommendations',
          ],
          extraClauses: [
            'sections 3/4/5 explicitly say "N/A — <reason>" when the classification makes them inapplicable (a placeholder left blank is a failure, an explicit N/A is not), and any lab-only Core Web Vitals scorecard labels INP as the TBT proxy.',
          ],
        }),
        maxRuns: 2,
        outcomes: [
          { label: 'approved', nextStepName: '8. Finalize report', default: true },
          { label: 'rework', nextStepName: '6. Composite score + recommendations' },
        ],
      },
      {
        type: 'work',
        name: '8. Finalize report',
        prompt: STEP7_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
