// Documentation-audit pipeline. Classifies docs by the Diátaxis framework
// (Tutorials / How-To / Reference / Explanation, via the Diátaxis compass),
// scores README quality against standard-readme + Awesome-README, and flags
// stale or contradictory docs. REPORT-ONLY — no code changes. A judge
// CheckStep validates the report before the run finishes.
//
// References:
// - Diátaxis (incl. the compass): https://diataxis.fr/ ; https://diataxis.fr/compass/
// - standard-readme spec: https://github.com/RichardLitt/standard-readme/blob/master/spec.md
// - Awesome README: https://github.com/matiassingers/awesome-readme
// - Badge impact (ICSE 2018, npm): https://cmustrudel.github.io/papers/icse18badges.pdf
// - Docs as code: https://www.writethedocs.org/guide/docs-as-code/
//
// IMPORTANT: keep this file pure (no fs / no env). Imported on the hot path
// of `App` mount via the default-pipelines registry.

import type { Pipeline } from '../types.js';
import {
  knowledgeProtocol,
  persistenceCheck,
  reportJudgeCondition,
  targetsRecon,
  KNOWLEDGE_OPTIONAL_FIELDS_NOTE,
  KNOWLEDGE_ORDERING_NOTE,
} from './knowledge-protocol.js';

const DOCS_TARGETS_PATH = '.huu/audits/docs-targets.json';
const DOCS_TARGETS_MAX_FILES = 30;

export const DEFAULT_PIPELINE_FILENAME = 'huu-docs-audit.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Docs Audit';

const FAQ_PATH = './.huu/audits/docs-faq.json';
const FAQ_SCHEMA_LINE =
  '{ "summary": "<=256 chars", "knowledge": "<=5000 chars", "path": "<doc file>", "category": "diataxis|readme|staleness|api-doc|recommendation", "severity": "info|warn|critical" }';

const STEP1_PROMPT = `You are huu's documentation-audit bootstrap agent. Goal: enumerate every documentation artifact in the repo, write \`.huu/audits/docs.md\` with the audit scaffold, and initialize \`.huu/audits/docs-faq.json\` as the per-file finding store.

=== STEP 0 — REPORT-ONLY HARD RULE ===
You may NOT modify any file in the repo OTHER than the audit artifacts under \`.huu/audits/\` (and \`.huu/audits/.tmp/\` for working files) plus the single \`.gitignore\` adjustment described below. If a tool requires installation, use \`npx --yes <tool>\` (Node), \`pipx run <tool>\` (Python), or vendored binaries under \`$HOME/.huu/bin/\`. NEVER touch package.json, requirements.txt, pyproject.toml, Cargo.toml, go.mod, lockfiles, or any production source. Create the output directory with \`mkdir -p .huu/audits/.tmp/docs\` before writing.

${persistenceCheck('audits')}

=== STEP 1 — Enumerate documentation ===
Find every file that is documentation. Cast a wide net:
- README*, CHANGELOG*, CONTRIBUTING*, CODE_OF_CONDUCT*, SECURITY*, LICENSE* at the repo root.
- \`docs/\`, \`doc/\`, \`documentation/\`, \`site/\` recursively.
- \`*.md\`, \`*.mdx\`, \`*.rst\`, \`*.adoc\`, \`*.txt\` anywhere under the repo (excluding \`node_modules\`, \`dist\`, \`build\`, \`.git\`, \`vendor\`, \`target\`, \`__pycache__\`).
- Inline API docs: count of files with JSDoc (\`/** */\`), TSDoc, Python docstrings (\`"""..."""\`), Rustdoc (\`///\`), Javadoc.

Write the list to \`./.huu/audits/.tmp/docs/files.txt\` (one path per line, sorted). This is a working file — step 6 may delete it at the end.

=== STEP 2 — Detect canonical files ===
Note presence/absence of:
- README at repo root (any case).
- CHANGELOG.
- CONTRIBUTING.
- LICENSE.
- CODE_OF_CONDUCT.
- SECURITY.
- A docs directory (\`docs/\`).

=== STEP 3 — Write .huu/audits/docs.md scaffold AT THE ROOT ===
Path: \`./.huu/audits/docs.md\`. Required structure (English, no fluff):

# .huu/audits/docs.md — Documentation audit

> Audit generated by huu's Docs Audit pipeline. Report-only — no source code was modified.

## 1. Inventory
- Total doc files: <N>
- Markdown / RST / AsciiDoc breakdown: <numbers>
- Canonical files present: README=<yes/no>, CHANGELOG=<yes/no>, CONTRIBUTING=<yes/no>, LICENSE=<yes/no>, CODE_OF_CONDUCT=<yes/no>, SECURITY=<yes/no>
- Inline API doc coverage estimate: <N public exports / N documented> (filled in by the API-doc-coverage scan)

## 2. Diátaxis classification
(filled in by step 2 of the audit)

## 3. README scorecard
(filled in by step 3 of the audit)

## 4. Staleness scan
(filled in by step 4)

## 5. API doc coverage
(filled in by the API-doc-coverage scan)

## 6. Recommendations
(filled in by step 6)

## 7. Validation
(filled in by the final step after the judge approves)

=== STEP 4 — Initialize .huu/audits/docs-faq.json ===
Path: \`./.huu/audits/docs-faq.json\`.
If absent: write \`[]\` + trailing newline.
If present and a valid array: leave untouched.
If present and corrupted: replace with \`[]\` and note in commit message.

Schema per entry (appended by later steps):
\`\`\`json
${FAQ_SCHEMA_LINE}
\`\`\`
${KNOWLEDGE_OPTIONAL_FIELDS_NOTE}

=== HARD RULES ===
- No source-code changes outside the new files above + \`.huu/audits/.tmp/docs/files.txt\`.
- DO NOT delete or move existing docs in this step.
- Be language-agnostic — do not assume Node.js.`;

const STEP2_PROMPT = `You are at step 2 — Diátaxis classification. Goal: classify every doc enumerated in \`.huu/audits/.tmp/docs/files.txt\` against the Diátaxis quadrants, append findings to \`.huu/audits/docs-faq.json\`, and populate section "2. Diátaxis classification" of \`.huu/audits/docs.md\`.

=== Diátaxis primer (https://diataxis.fr/) ===
Four orthogonal documentation kinds, one per user need:
- **Tutorial** — learning-oriented; a lesson that takes a student by the hand through a learning experience.
- **How-To Guide** — goal-oriented; addresses a real-world problem for a competent user with practical directions.
- **Reference** — information-oriented; neutral technical description (facts) the user consults to do things correctly (API specs, CLI flags, config schemas).
- **Explanation** — understanding-oriented; context, background, "why" decisions were made (ADRs, architecture overviews, design rationale).

Classify with the **Diátaxis compass** (https://diataxis.fr/compass/) — two questions per doc:
1. Does the content inform **action** (practical steps) or **cognition** (theoretical knowledge)?
2. Does it serve the **acquisition** of skill (study) or its **application** (work)?
action+acquisition → tutorial · action+application → how-to · cognition+application → reference · cognition+acquisition → explanation.

Plus a fifth bucket:
- **Unclassified** — doesn't fit cleanly; could be a mix or marketing.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/.tmp/docs/files.txt\` (built in step 1).
- \`./.huu/audits/docs.md\` (scaffold).
- \`./.huu/audits/docs-faq.json\` (may be empty).

If any are missing: abort with a clear error.

=== STEP 2 — Classify each doc ===
For each file:
1. Read the first ~200 lines (enough to identify the genre).
2. Decide ONE primary classification: tutorial / how-to / reference / explanation / unclassified.
3. Score quality 0–10 against its category's expectations:
   - Tutorial: starts with a concrete goal, hand-holds, has no detours, gives a real result.
   - How-To: lists prerequisites, gives ordered steps, no fluff.
   - Reference: complete coverage of the thing described, neutral tone, structured.
   - Explanation: explains "why", not "how"; links to references and how-tos rather than inlining them.
4. APPEND to \`.huu/audits/docs-faq.json\`:
   \`\`\`json
   { "summary": "<one-line summary of the doc>", "knowledge": "<why this classification, what's weak, what's strong>", "path": "<file>", "category": "diataxis", "severity": "<info|warn|critical>" }
   \`\`\`
   Severity heuristic: info = clearly fits a quadrant and is decent; warn = misclassified or low quality; critical = the file claims to be one type but is mostly another (the most damaging anti-pattern per Diátaxis).

=== STEP 3 — Update .huu/audits/docs.md section "2. Diátaxis classification" ===
Replace the placeholder with a markdown table:

| File | Type | Score (0-10) | Notes |
|---|---|---|---|
| README.md | reference | 5 | mixes tutorial and reference (anti-pattern) |
| docs/getting-started.md | tutorial | 8 | strong |
| ... | | | |

Plus a summary block:
\`\`\`
Tutorials: X
How-to: X
Reference: X
Explanation: X
Unclassified: X
Diátaxis anti-patterns flagged: X (see findings in .huu/audits/docs-faq.json)
\`\`\`

=== HARD RULES ===
- Append-only to \`.huu/audits/docs-faq.json\` — never rewrite from scratch.
- Re-read the FAQ file before each append (parallel agents may have appended too).
- Update ONLY section "2" of \`.huu/audits/docs.md\` — leave the other sections untouched.
- DO NOT modify the docs themselves.`;

const STEP3_PROMPT = `You are at step 3 — README quality scorecard. Goal: score the project's README against a rubric grounded in standard-readme (https://github.com/RichardLitt/standard-readme/blob/master/spec.md) and Awesome-README (https://github.com/matiassingers/awesome-readme), append findings, and populate section "3. README scorecard" of \`.huu/audits/docs.md\`.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: step 2 already classified the README under category "diataxis" — read that finding first; a README flagged as a tutorial/reference mix should lose points on the relevant checks below, citing the prior finding.

=== STEP 1 — Locate the README ===
Search case-insensitively for \`README*\` at the repo root. If multiple (e.g. README.md + README.es.md), score the English one if present; otherwise the largest by byte size. If NO README exists, write the scorecard with all checks failing and severity=critical.

=== STEP 2 — Rubric (10 checks, 10 pts each — score out of 100) ===
For each, give 10 if present and well-done, 5 if present but weak, 0 if absent.

1. **Title** — clear project name as an H1 (standard-readme: required, file named README.md).
2. **One-line description** — a single concise sentence under the title that answers "what is this" (standard-readme: required).
3. **Badges** — at least one ASSESSMENT badge (build/coverage) near the top. (ICSE 2018 npm study: build/coverage badges correlate with larger test suites; "assessment" badges signal quality better than popularity ones.)
4. **Visual demo** — screenshot, GIF, ASCII art, or diagram showing the product in action (the single most recurring element across Awesome-README entries).
5. **Installation** — a copy-pasteable install/setup section (standard-readme: required for non-doc repos).
6. **Usage / examples** — at least one real, runnable example (standard-readme: required; code examples should lint).
7. **Features** — bulleted list of key capabilities.
8. **Documentation links** — links to further docs (tutorials, API, etc.; a TOC when the README exceeds ~100 lines — standard-readme rule).
9. **Contributing** — a section or link explaining how to contribute (standard-readme: required).
10. **License** — explicit license mention near the bottom (standard-readme: required).

Also note (no points, one line in the report): does the section ORDER roughly follow standard-readme (title → description → TOC → install → usage → contributing → license)?

Total score → 0–100. Color grade:
- >= 80 → \`green\`
- 50–79 → \`yellow\`
- < 50 → \`red\`

=== STEP 3 — Append finding ===
\`\`\`json
{ "summary": "README scorecard: <N>/100", "knowledge": "<itemized breakdown of which checks passed/failed and why>", "path": "<readme path or 'none'>", "category": "readme", "severity": "<info if >=80, warn if 50-79, critical if <50>" }
\`\`\`

=== STEP 4 — Update .huu/audits/docs.md section "3. README scorecard" ===
Replace the placeholder with:

| Check | Score | Notes |
|---|---|---|
| Title | 10/10 | Clear H1 |
| One-line description | 5/10 | Vague |
| Badges | 0/10 | None |
| ... | | |
| **Total** | **<N>/100** | grade: <green/yellow/red> |

=== HARD RULES ===
- Append-only to \`.huu/audits/docs-faq.json\`.
- DO NOT modify the README itself.
- Update ONLY section "3" of \`.huu/audits/docs.md\`.`;

const STEP4_PROMPT = `You are at step 4 — staleness scan. Goal: detect docs that reference removed files, contradict current code, or have not been touched in > 12 months. Append findings and populate section "4. Staleness scan" of \`.huu/audits/docs.md\`.

${knowledgeProtocol(FAQ_PATH, FAQ_SCHEMA_LINE)}
In particular: low-scoring docs from steps 2–3 (categories "diataxis" and "readme") are the most likely to also be stale — check those first and cross-reference the prior finding in your "knowledge" field.

=== STEP 1 — Build a list of doc files to scan ===
Use \`.huu/audits/.tmp/docs/files.txt\` from step 1. If absent: re-enumerate (same heuristic).

=== STEP 2 — For each doc file, run three checks ===

**Check A — Dead references**
Extract every code-style reference: backtick'd file paths, code-block paths, links like \`[name](relative/path)\`, and command names. For each:
- If it looks like a repo file path (\`src/...\`, \`./...\`, \`../...\`, \`packages/...\`): test \`test -e <path>\`. If missing → finding (severity warn).
- If it looks like a CLI command (\`npm run X\`, \`make X\`, \`pnpm X\`): check the project's manifest for that script. If missing → finding (severity warn).
- If it's an external URL: skip (network out of scope here).

**Check B — Code contradiction**
For docs that include CLI snippets in fenced code blocks, sample-check 3–5 commands at random. Heuristic test: does the command's binary exist in the project / on PATH? E.g. doc says \`npm run dev\` but only \`npm start\` is defined.

**Check C — Age (last commit touching the file)**
Use git: \`git log -1 --format=%at -- <path>\`. If the timestamp is older than 365 days, that's an age finding (severity info; warn only if the file also appears stale by checks A/B).

=== STEP 3 — Append findings ===
For EACH finding from any of the three checks:
\`\`\`json
{ "summary": "<one-line: e.g. 'docs/setup.md references missing src/legacy/db.ts'>", "knowledge": "<full context: which line of the doc, what the reference was, what's actually there now>", "path": "<doc path>", "category": "staleness", "severity": "info|warn|critical" }
\`\`\`

Severity:
- critical: doc contradicts current code in a way that would actively mislead a user (e.g. install instructions point to a removed file).
- warn: dead reference or contradiction that's unlikely to actively break anyone, but is wrong.
- info: just age.

=== STEP 4 — Update .huu/audits/docs.md section "4. Staleness scan" ===
Replace the placeholder with a table:

| Doc | Finding | Severity | Notes |
|---|---|---|---|

Plus summary counts (critical/warn/info).

=== HARD RULES ===
- Append-only to \`.huu/audits/docs-faq.json\`.
- DO NOT modify the docs.
- DO NOT modify code referenced by the docs.`;

const STEP_RECON_PROMPT = `${targetsRecon({
  role: "huu's API-doc-coverage target selector",
  purpose:
    'checking inline API-doc coverage (JSDoc/TSDoc/docstring/Rustdoc/Javadoc) on',
  prefer: [
    'files with a real public API surface — several exported functions / classes / types / components',
    'core modules and library entry points over leaf scripts, constants, or config',
    'public-facing code a consumer would import (the docs that matter most when missing)',
  ],
  hintGuide:
    'name the key public exports here whose doc-comments matter most (and whether they currently look documented)',
  maxFiles: DOCS_TARGETS_MAX_FILES,
})}

=== BEFORE YOU START ===
Read \`./.huu/audits/docs.md\` for the doc inventory the earlier steps built (section 1's totals and the canonical-files list tell you where the real source modules live). This step writes ONLY the target list; the per-file API-doc-coverage scan that follows does the actual finding.`;

const STEP5_PROMPT = `You are the API-doc-coverage scan for ONE file: \`$file\`. You are one of many agents running in parallel; your whole job is this single file.

The recon step chose this file deliberately and left you a lead — start there: $hint

=== STEP 0 — SKIP RULE ===
SKIP IMMEDIATELY (no findings, no FAQ append) if \`$file\` matches: \`node_modules/\`, \`dist/\`, \`build/\`, \`out/\`, \`coverage/\`, \`.git/\`, \`vendor/\`, \`target/\`, \`__pycache__/\`, \`*.generated.*\`, \`*.min.js\`, \`*.min.css\`, \`*.d.ts\`, \`*.lock\`, \`*.snap\`.

=== STEP 1 — Read \`$file\` and identify language ===
Use the extension and content to determine which doc-comment style applies:
- TypeScript / JavaScript: JSDoc / TSDoc (\`/** */\` above the export).
- Python: triple-quoted docstring as the first statement of the function/class.
- Rust: \`///\` or \`/** */\` above the item.
- Go: \`//\` line(s) directly above the exported identifier (idiomatic Go doc style).
- Java / Kotlin: Javadoc / KDoc (\`/** */\` above the method/class).
- Ruby: \`#\` lines above the method.
- C / C++: Doxygen \`/** */\` or \`/// \` above the declaration.

If the language isn't detected, finish silently with no findings.

=== STEP 2 — Enumerate public exports ===
Per language:
- TypeScript: any \`export\` (named/default), top-level functions/classes/interfaces. Skip internal helpers (those prefixed with \`_\`).
- Python: top-level \`def\` / \`class\` (skip names starting with \`_\`).
- Rust: items marked \`pub\` / \`pub(crate)\`.
- Go: identifiers that start with an uppercase letter at package level.
- Java: \`public\` methods/classes.

=== STEP 3 — Check doc presence per export ===
For each export:
- Is there an immediately-adjacent doc-comment of the right style? Yes/no.
- If yes, does it have at least one sentence of substance (not just \`/** Foo */\` re-stating the name)?

=== STEP 4 — Append ONE finding per file ===
\`\`\`json
{ "summary": "$file: <documented>/<total> public exports have substantive docs", "knowledge": "<list of undocumented exports + 1-line note per missing doc>", "path": "$file", "category": "api-doc", "severity": "info|warn|critical" }
\`\`\`

Severity:
- info: 100% documented.
- warn: >= 50% documented.
- critical: < 50% of public exports documented.

=== HARD RULES ===
- ONLY analyze \`$file\` — do not touch other files.
- DO NOT modify \`$file\`.
- Append-only to \`.huu/audits/docs-faq.json\` (re-read before appending — other agents are running in parallel).`;

const STEP6_PROMPT = `You are the final agent — step 6. Goal: consolidate findings from \`.huu/audits/docs-faq.json\` into the "5. API doc coverage" and "6. Recommendations" sections of \`.huu/audits/docs.md\`, and clean up working files.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/docs.md\` (sections 1–4 already populated).
- \`./.huu/audits/docs-faq.json\` (all findings).

=== STEP 2 — Compute API doc coverage section "5" ===
Aggregate findings with \`category: "api-doc"\`:
- Total public exports across all files = sum of "total" values from findings.
- Total documented = sum of "documented" values.
- Per-file table sorted by undocumented count descending (top 20).

Write into section "5. API doc coverage":

\`\`\`
Total public exports: <N>
Documented: <M> (<percentage>%)
Files with critical gaps (< 50% docs):
| File | Documented / Total | Severity |
|---|---|---|
| src/foo.ts | 3/12 | critical |
| ... | | |
\`\`\`

=== STEP 3 — Compute section "6. Recommendations" ===
Synthesize from ALL findings into prioritized recommendations.
${KNOWLEDGE_ORDERING_NOTE}

### Critical (do these first)
- Bullet for each critical-severity finding, grouped by category. Include the path and a 1-line action.

### Warnings (do these next)
- Same format for warn findings.

### Diátaxis gaps
- Quadrants that have 0 or near-0 docs → recommend creating at least one doc in each missing quadrant.
- Files flagged as misclassified (warn/critical under category "diataxis") → recommend splitting them per Diátaxis.

### Suggested next steps (template)
- "Add a Tutorial: docs/tutorials/quickstart.md — walks a first-time user through running the project end-to-end."
- "Add a Reference: docs/reference/cli.md — exhaustive flag-by-flag table for the CLI."
- "Add an Explanation: docs/explanation/architecture.md — why the layered design and how the pieces fit."

=== STEP 4 — Clean up ===
- Delete \`./.huu/audits/.tmp/docs/files.txt\` (working file).
- Keep \`.huu/audits/docs.md\` and \`.huu/audits/docs-faq.json\`.

=== HARD RULES ===
- DO NOT modify any docs other than \`.huu/audits/docs.md\` itself.
- DO NOT modify source code.
- Final \`.huu/audits/docs.md\` should be a complete, self-contained report a human can read top-to-bottom.
- The counts you cite MUST match the FAQ entries exactly — the validation judge recounts them.`;

const STEP8_PROMPT = `You are the final agent — step 8 (post-validation). The judge approved the report. Goal: stamp section "7. Validation" of \`.huu/audits/docs.md\` and leave the working tree clean.

=== STEP 1 — Stamp the validation section ===
Replace the "## 7. Validation" placeholder with:
\`\`\`
Validated: <UTC timestamp> · findings: <total> (critical <X> / warn <Y> / info <Z>) · README score <N>/100 · sections 1–6 complete.
Validation gate: judge CheckStep ("approved" required to reach this step; "rework" loops back to consolidation, max 2 judge runs).
\`\`\`
Numbers MUST come from re-reading \`.huu/audits/docs-faq.json\` and the report — do not invent them. Be idempotent: if the section is already stamped (a rework loop ran twice), overwrite it with fresh numbers.

=== STEP 2 — Exit hygiene ===
- Confirm \`./.huu/audits/.tmp/docs/\` holds no leftovers (step 6 deletes files.txt; remove anything else, keep the directory).
- Confirm \`git status --porcelain\` shows changes only under \`.huu/\` (plus at most the permitted \`.gitignore\` adjustment).

=== HARD RULES ===
- DO NOT modify the findings or the recommendations — stamp only.
- DO NOT touch production files or the project's docs.`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Enumerate docs and scaffold .huu/audits/docs.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Diataxis classification',
        prompt: STEP2_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '3. README quality scorecard',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '4. Staleness scan',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. Select API-doc targets',
        prompt: STEP_RECON_PROMPT,
        files: [],
        scope: 'project',
        // huu appends the huu-memory-v1 MEMORY CONTRACT (path + format + cap).
        produces: DOCS_TARGETS_PATH,
      },
      {
        type: 'work',
        name: '6. API doc coverage for $file',
        prompt: STEP5_PROMPT,
        files: [],
        // Autonomous file set from the recon step — no per-file picker.
        scope: 'memory',
        filesFrom: DOCS_TARGETS_PATH,
        maxFiles: DOCS_TARGETS_MAX_FILES,
      },
      {
        type: 'work',
        name: '7. Consolidate report and cleanup',
        prompt: STEP6_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'check',
        name: '8. Validate report',
        condition: reportJudgeCondition({
          reportPath: '.huu/audits/docs.md',
          faqPath: '.huu/audits/docs-faq.json',
          requiredSections: [
            '1. Inventory',
            '2. Diátaxis classification',
            '3. README scorecard',
            '4. Staleness scan',
            '5. API doc coverage',
            '6. Recommendations',
          ],
          extraClauses: [
            'the Diátaxis summary block in section 2 accounts for every file listed in the classification table, and the README scorecard total equals the sum of its 10 checks.',
          ],
        }),
        maxRuns: 2,
        outcomes: [
          { label: 'approved', nextStepName: '9. Finalize report', default: true },
          { label: 'rework', nextStepName: '7. Consolidate report and cleanup' },
        ],
      },
      {
        type: 'work',
        name: '9. Finalize report',
        prompt: STEP8_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
