// Code-quality-audit pipeline. Sonar-style report: cyclomatic complexity,
// cognitive complexity (estimated), function/file size, parameter count,
// nesting depth, duplication, dead code. REPORT-ONLY.
//
// Thresholds (baked into prompts):
// - Cyclomatic complexity > 10 = warn, > 20 = high-risk (SonarSource).
// - Function length > 50 LOC = warn.
// - Parameter count > 5 = warn.
// - Nesting depth > 4 = warn.
// - Duplication > 3% = warn.

import type { Pipeline } from '../types.js';

export const DEFAULT_PIPELINE_FILENAME = 'huu-quality-audit.pipeline.json';
export const DEFAULT_PIPELINE_NAME = 'huu Quality Audit';

const STEP1_PROMPT = `You are huu's code-quality-audit bootstrap agent. Goal: detect the project's language(s), make ephemeral complexity tools available where possible, write \`.huu/audits/quality.md\` scaffold and initialize \`.huu/audits/quality-faq.json\`.

=== STEP 0 — REPORT-ONLY HARD RULE ===
You may NOT modify any file in the repo OTHER than the audit artifacts under \`.huu/audits/\` (and \`.huu/audits/.tmp/\` for working files). If a tool requires installation, use \`npx --yes <tool>\` (Node), \`pipx run <tool>\` (Python), or vendored binaries under \`$HOME/.huu/bin/\`. NEVER touch package.json, requirements.txt, pyproject.toml, Cargo.toml, go.mod, lockfiles, or any production source. Create the output directory with \`mkdir -p .huu/audits/.tmp/quality\` before writing.

=== STEP 1 — Detect language(s) ===
Walk the repo and tally source files by extension. Identify the top language(s) by file count. Common targets:
- TypeScript/JavaScript: \`.ts\`, \`.tsx\`, \`.js\`, \`.jsx\`.
- Python: \`.py\`.
- Go: \`.go\`.
- Rust: \`.rs\`.
- Java: \`.java\`.
- Kotlin: \`.kt\`.
- Ruby: \`.rb\`.
- C/C++: \`.c\`, \`.cc\`, \`.cpp\`, \`.h\`, \`.hpp\`.
- C#: \`.cs\`.

Skip generated / vendored directories: \`node_modules\`, \`dist\`, \`build\`, \`out\`, \`vendor\`, \`target\`, \`__pycache__\`, \`.git\`, \`coverage\`.

=== STEP 2 — Make complexity tools available (ephemeral only) ===
EPHEMERAL ONLY. Use one-shot runners that DON'T modify the repo's manifests:

- TypeScript/JavaScript:
  - \`npx --yes eslint <args>\` (no install — npx caches under ~/.npm).
  - \`npx --yes eslint-plugin-sonarjs <args>\`.
  - Duplication: \`npx --yes jscpd <args>\`.
  - Unused exports: \`npx --yes ts-unused-exports <args>\`.
- Python:
  - \`pipx run radon <args>\` (cyclomatic + maintainability).
  - \`pipx run vulture <args>\` (dead code).
- Go: prefer \`go vet ./...\` (already in toolchain). For gocyclo, install to \`$HOME/.huu/bin/\` (\`GOBIN=$HOME/.huu/bin go install github.com/fzipp/gocyclo/cmd/gocyclo@latest\`) — NOT to the project.
- Rust: use \`cargo clippy\` only if already configured. Skip if not.
- Java: skip — toolchain installs are heavy and project-coupled.

If a tool isn't reachable (offline / no pipx / no node): WRITE an info-severity finding to the FAQ and fall back to grep/awk heuristics. The pipeline NEVER hard-fails on missing tooling.

=== STEP 3 — Write .huu/audits/quality.md scaffold ===
Path: \`./.huu/audits/quality.md\`. Required structure:

# .huu/audits/quality.md — Code quality audit

> Report-only audit generated by huu's Quality Audit pipeline.
> Thresholds: cyclomatic > 10 = warn, > 20 = high-risk; function > 50 LOC = warn; params > 5 = warn; nesting > 4 = warn; duplication > 3% = warn.

## 1. Project stats
- Languages detected: <list with file counts>
- Tools available: <list of complexity tools that successfully ran>
- Tools unavailable: <list with the reason>

## 2. Complexity hotspots
(filled in by step 2)

## 3. Duplication
(filled in by step 3)

## 4. Dead code
(filled in by step 4)

## 5. Composite score
(filled in by step 5)

## 6. Recommendations
(filled in by step 5)

=== STEP 4 — Initialize .huu/audits/quality-faq.json ===
Path: \`./.huu/audits/quality-faq.json\`. Same idempotent rules as other huu audits:
- Missing: write \`[]\` + newline.
- Existing valid array: leave alone.
- Corrupted: replace with \`[]\` + note in commit.

Schema:
\`\`\`json
{ "summary": "<=256>", "knowledge": "<=5000>", "path": "<file or 'global'>", "category": "complexity|duplication|dead-code|size|composite", "severity": "info|warn|critical", "metric": { "name": "cyclomatic", "value": 17 } }
\`\`\`

=== HARD RULES ===
- DO NOT modify production source code.
- DO NOT touch CI/CD config.
- The only outputs are .huu/audits/quality.md + .huu/audits/quality-faq.json + (optional) package.json devDeps additions for installed tools.`;

const STEP2_PROMPT = `You are at step 2 — per-file complexity scan of \`$file\`. Goal: compute metrics (cyclomatic, function length, parameter count, nesting depth) for \`$file\` and append findings to \`.huu/audits/quality-faq.json\`. NO code changes.

=== STEP 0 — SCOPE NOTE + SKIP RULE ===
This step spawns one agent per selected file. The pipeline caps total nodes at \`maxNodeExecutions: 50\` (~45 files on a 5-step pipeline). If you are auditing a larger repo, narrow your file selection with Smart Select in the file picker.

SKIP IMMEDIATELY (no findings, no FAQ append) if \`$file\` matches: \`node_modules/\`, \`dist/\`, \`build/\`, \`out/\`, \`coverage/\`, \`.git/\`, \`vendor/\`, \`target/\`, \`__pycache__/\`, \`*.generated.*\`, \`*.min.js\`, \`*.min.css\`, \`*.d.ts\`, \`*.lock\`, \`*.snap\`.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/quality.md\` (scaffold; check section 1 for which tools are available).
- \`./.huu/audits/quality-faq.json\` (may be empty or have prior findings).
- \`$file\` (the source file to analyze).

=== STEP 2 — Pick the appropriate tool ===
By extension, in order of preference:
- \`.ts/.tsx/.js/.jsx\`: try \`npx eslint --no-eslintrc --rule '{"complexity": ["error", {"max": 10}]}' "$file"\`. Fallback: AST-free heuristic (count if/else/case/for/while/&&/||/?: in the file).
- \`.py\`: \`radon cc -s -j "$file"\` (JSON output). Fallback: heuristic.
- \`.go\`: \`gocyclo "$file"\`. Fallback: heuristic.
- \`.rs\`: \`cargo clippy -- -W cognitive_complexity\` (slow; only if cargo present). Fallback: heuristic.
- \`.java/.kt\`: heuristic only (avoid heavyweight setup).
- Other: heuristic only.

=== STEP 3 — Heuristic fallback (when no tool ran) ===
Per FUNCTION (best-effort regex; not perfect but consistent):
- Cyclomatic ≈ 1 + count of \`\\bif\\b|\\belse\\b|\\bcase\\b|\\bwhen\\b|\\bfor\\b|\\bwhile\\b|&&|\\|\\||\\?\` inside the function body.
- Function length = lines of code between the opening and closing brace (or Python indent block).
- Parameter count = count of commas in the signature + 1 (0 if signature is empty).
- Nesting depth = max indentation level reached inside the function body.

=== STEP 4 — Score and append findings ===
For each function found:
- Cyclomatic > 20 → severity critical, category "complexity".
- Cyclomatic > 10 → severity warn.
- Length > 50 LOC → severity warn, category "size".
- Length > 200 LOC → severity critical.
- Parameter count > 5 → severity warn, category "size".
- Nesting depth > 4 → severity warn, category "complexity".

Append ONE finding per problematic function:
\`\`\`json
{ "summary": "<file>:<funcName> cyclomatic=17", "knowledge": "<details>", "path": "$file", "category": "complexity", "severity": "warn", "metric": { "name": "cyclomatic", "value": 17 } }
\`\`\`

If \`$file\` has zero findings, append ONE info-severity summary saying so:
\`\`\`json
{ "summary": "$file: clean (all metrics under thresholds)", "knowledge": "...", "path": "$file", "category": "composite", "severity": "info" }
\`\`\`

=== HARD RULES ===
- DO NOT modify \`$file\`.
- DO NOT touch other files.
- Append-only to \`.huu/audits/quality-faq.json\` (re-read before each append; parallel agents).`;

const STEP3_PROMPT = `You are at step 3 — duplication scan (whole-project). Goal: find duplicated code blocks across the codebase, append findings to \`.huu/audits/quality-faq.json\`, populate section "3. Duplication" of \`.huu/audits/quality.md\`. NO code changes.

=== STEP 1 — Pick the tool ===
- If \`jscpd\` is installed: \`npx --yes jscpd --min-lines 8 --min-tokens 50 --threshold 3 --reporters json --output ./.huu/audits/.tmp/quality/jscpd-report .\`. Read the JSON report.
- If \`pmd\` is available: \`pmd cpd --minimum-tokens 50 --files <src> --format text\`.
- Fallback: a fingerprint heuristic — hash sliding 10-line windows (normalized: collapse whitespace, strip comments) across all source files; report any hash collision as a duplication candidate.

=== STEP 2 — For each duplication >= 8 lines ===
Append:
\`\`\`json
{ "summary": "Duplication: <fileA>:Lx-Ly ~ <fileB>:Lx-Ly (<N> lines)", "knowledge": "<the duplicated snippet, redacted to 200 chars, plus a hint about which Fowler refactoring applies (Extract Function, Pull Up Method, etc.)>", "path": "<fileA>", "category": "duplication", "severity": "warn", "metric": { "name": "duplicate_lines", "value": <N> } }
\`\`\`

Severity: warn unless duplication > 50 lines (critical).

=== STEP 3 — Compute project-wide duplication percentage ===
Approximate: (duplicated lines) / (total source LOC). If >= 3% → write a critical summary finding under category "duplication".

=== STEP 4 — Update .huu/audits/quality.md section "3. Duplication" ===
Replace the placeholder with:

\`\`\`
Total source LOC: <N>
Duplicated LOC: <M>
Duplication %: <X>%
Threshold: 3% (warn)
Top 10 duplications:
| Pair | Lines | Suggested refactoring |
|---|---|---|
| src/foo.ts:42-67 ↔ src/bar.ts:88-113 | 25 | Extract Function (https://refactoring.com/catalog/extractFunction.html) |
| ... | | |
\`\`\`

=== Cleanup ===
Delete the \`.huu-jscpd-report\` file (working artifact) if it was created.

=== HARD RULES ===
- DO NOT modify source code.
- DO NOT install additional tools at this step (step 1 already tried).
- Update ONLY section "3" of \`.huu/audits/quality.md\`.`;

const STEP4_PROMPT = `You are at step 4 — dead-code detection (whole-project). Goal: list unused exports, unused dependencies, unused private helpers. Append findings, populate section "4. Dead code" of \`.huu/audits/quality.md\`. NO code changes.

=== STEP 1 — Pick tools per stack ===
- TS/JS:
  - \`npx --yes ts-unused-exports tsconfig.json\` if tsconfig present.
  - \`npx --yes depcheck\` for unused dependencies (npm packages).
  - \`npx --yes knip --reporter json\` if installable (catches all: deps, exports, files).
- Python: \`vulture <pkg-dir> --min-confidence 80\`.
- Go: \`go vet ./...\` + \`staticcheck -checks U1000 ./...\` if available.
- Rust: \`cargo udeps\` if installed; \`cargo clippy -- -W dead_code\`.
- Fallback: grep for exported symbols that have ZERO references in the rest of the codebase (cheap proxy).

=== STEP 2 — For each dead-code finding ===
\`\`\`json
{ "summary": "Unused export <symbol> in <file>", "knowledge": "<which tool found it, confidence, any context>", "path": "<file>", "category": "dead-code", "severity": "warn|info", "metric": { "name": "unused", "value": 1 } }
\`\`\`

Severity:
- warn: exported symbol with zero references inside the repo.
- info: unused dependency in package.json / requirements.txt / Cargo.toml.
- critical: rarely used — reserved for cases like the entire \`src/legacy/\` folder being dead.

=== STEP 3 — Update .huu/audits/quality.md section "4. Dead code" ===
Replace the placeholder with a table of the top 30 findings.

=== HARD RULES ===
- DO NOT delete anything. This is detection only.
- DO NOT update package.json's deps even if depcheck found unused ones.
- DO NOT touch source code.`;

const STEP5_PROMPT = `You are the final agent — step 5. Goal: read all findings from \`.huu/audits/quality-faq.json\`, compute a composite quality score, populate sections "5. Composite score" and "6. Recommendations" of \`.huu/audits/quality.md\`, and add a quality badge to README.md.

=== STEP 1 — Read inputs ===
- \`./.huu/audits/quality.md\` (sections 1–4 already populated).
- \`./.huu/audits/quality-faq.json\` (all findings).

=== STEP 2 — Compute composite quality score (0-100) ===
Start at 100. Subtract per finding:
- critical: -5 each (cap at -50 total).
- warn: -1 each (cap at -30 total).
- info: 0.

Score floor: 0.

Per-file hotspot ranking: rank files by sum of severity weights (critical=5, warn=1). Top 10 = hotspot list.

=== STEP 3 — Update .huu/audits/quality.md section "5. Composite score" ===
Replace the placeholder with:

\`\`\`
Composite quality score: <N>/100
Grade: <A: 90+, B: 75-89, C: 60-74, D: 40-59, F: <40>

Findings by category:
- Complexity: <count> (critical: <X>, warn: <Y>)
- Duplication: <count>
- Dead code: <count>
- Size: <count>

Hotspot files (top 10):
| File | Critical | Warn | Composite weight |
|---|---|---|---|
| src/orchestrator/runner.ts | 3 | 7 | 22 |
| ... | | | |
\`\`\`

=== STEP 4 — Update .huu/audits/quality.md section "6. Recommendations" ===
Group findings and write actionable recommendations, each linked to a Fowler refactoring catalog entry where applicable:

### Critical (fix first)
- "src/foo.ts:bar() has cyclomatic 27 — apply Extract Function (https://refactoring.com/catalog/extractFunction.html) and Decompose Conditional."

### Warnings
- "src/baz.ts:42 ↔ src/qux.ts:88 — 30 line duplication. Extract a shared helper."

### Improvements
- "10 unused exports in src/utils/ — verify with a grep and remove if truly dead."

=== HARD RULES ===
- DO NOT modify any production file. The only output is \`.huu/audits/quality.md\`.
- DO NOT change findings retroactively in the FAQ (append-only).
- If you computed a composite score, mention it as a markdown line in the report itself (e.g. "Composite quality score: 76/100"). Do NOT add a README badge — the user can paste one manually if desired.`;

export function getDefaultPipeline(): Pipeline {
  return {
    name: DEFAULT_PIPELINE_NAME,
    maxRetries: 1,
    maxNodeExecutions: 50,
    steps: [
      {
        type: 'work',
        name: '1. Detect stack, install tools, scaffold .huu/audits/quality.md',
        prompt: STEP1_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '2. Per-file complexity scan: $file',
        prompt: STEP2_PROMPT,
        files: [],
        scope: 'per-file',
      },
      {
        type: 'work',
        name: '3. Project-wide duplication scan',
        prompt: STEP3_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '4. Dead-code detection',
        prompt: STEP4_PROMPT,
        files: [],
        scope: 'project',
      },
      {
        type: 'work',
        name: '5. Composite score + recommendations + badge',
        prompt: STEP5_PROMPT,
        files: [],
        scope: 'project',
      },
    ],
  } as Pipeline;
}

export function getDefaultPipelineFileContent(): string {
  return (
    JSON.stringify(
      {
        _format: 'huu-pipeline-v2',
        exportedAt: new Date().toISOString(),
        pipeline: getDefaultPipeline(),
      },
      null,
      2,
    ) + '\n'
  );
}
